yonadev/yona-server

appservice/src/intTest/groovy/nu/yona/server/BasicBuddyTest.groovy
appservice/src/intTest/groovy/nu/yona/server/CreateUserOnBuddyRequestTest.groovy
appservice/src/intTest/groovy/nu/yona/server/DisclosureTest.groovy
appservice/src/intTest/groovy/nu/yona/server/EditGoalsTest.groovy
appservice/src/main/java/nu/yona/server/messaging/rest/MessageController.java
appservice/src/main/java/nu/yona/server/subscriptions/rest/UserController.java
core/src/main/java/nu/yona/server/goals/service/GoalChangeMessageDTO.java
core/src/main/java/nu/yona/server/messaging/service/BuddyMessageDTO.java
core/src/main/java/nu/yona/server/messaging/service/BuddyMessageEmbeddedUserDTO.java
core/src/main/java/nu/yona/server/messaging/service/BuddyMessageLinkedUserDTO.java
core/src/main/java/nu/yona/server/messaging/service/DisclosureRequestMessageDTO.java
core/src/main/java/nu/yona/server/messaging/service/DisclosureResponseMessageDTO.java
core/src/main/java/nu/yona/server/messaging/service/MessageDTO.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyConnectRequestMessageDTO.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyConnectResponseMessageDTO.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyDisconnectMessageDTO.java

Till now, messages included an embedded User. This implies unnecessary overhead, has the user is available already as part of the buddy data.
The following messages now use a link to the user:
- BuddyConnectRequestMessage
- DisclosureRequestMessage
- DisclosureResponseMessage
- GoalChangeMessage
The following messages embed the user, as the user data might not be available in the buddy data (but now inside _embedded):
- BuddyConnectRequestMessage
- BuddyDisconnectMessage
Additional changes:
- The DisclosureRequestMessage does not embed the target anymore. There is a link, that's sufficient.
- The DisclosureResponseMessage now includes a "related" link for the target message

YD-196 Messages now include a link when possible

---

appservice/src/intTest/groovy/nu/yona/server/AbstractAppServiceIntegrationTest.groovy
appservice/src/intTest/groovy/nu/yona/server/EditGoalsTest.groovy
appservice/src/main/resources/static/swagger/swagger-spec.yaml
core/src/main/java/nu/yona/server/goals/service/BudgetGoalDTO.java
core/src/main/java/nu/yona/server/goals/service/GoalDTO.java
core/src/main/java/nu/yona/server/goals/service/TimeZoneGoalDTO.java

The property was already added earlier for inactivity support.
One question: Should we also refactor Message.creationTime to ZonedDateTime? That would be more consistent. Or the other way around, expose a Date here?

YD-159 Add creationTime to goal DTO

---

appservice/src/intTest/groovy/nu/yona/server/CreateUserOnBuddyRequestTest.groovy
appservice/src/main/resources/static/swagger/swagger-spec.yaml
core/src/main/java/nu/yona/server/subscriptions/service/BuddyDTO.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyService.java

* Added the tempPassword query parameter to the Swagger spec for GET and PUT /users/{id}
* Removed property userCreatedInviteURL from BuddyDTO
* Now generates password abcd in case e-mail is disabled
* The test now composes the invitation URL from the self-link of the buddy user and the abcd password.

YD-233 Standard temp password in test config

---

adminservice/src/main/java/nu/yona/server/goals/rest/ActivityCategoryController.java
analysisservice/src/main/java/nu/yona/server/analysis/rest/AnalysisEngineController.java
appservice/src/main/java/nu/yona/server/admin/rest/AdminController.java
appservice/src/main/java/nu/yona/server/analysis/rest/ActivityController.java
appservice/src/main/java/nu/yona/server/analysis/rest/AppActivityController.java
appservice/src/main/java/nu/yona/server/goals/rest/ActivityCategoryController.java
appservice/src/main/java/nu/yona/server/goals/rest/GoalController.java
appservice/src/main/java/nu/yona/server/messaging/rest/MessageController.java
appservice/src/main/java/nu/yona/server/subscriptions/rest/BuddyController.java
appservice/src/main/java/nu/yona/server/subscriptions/rest/NewDeviceRequestController.java
appservice/src/main/java/nu/yona/server/subscriptions/rest/PinResetRequestController.java
appservice/src/main/java/nu/yona/server/subscriptions/rest/UserController.java
core/src/main/java/nu/yona/server/rest/ErrorLoggingFilter.java
core/src/main/resources/templates/error.vm

Several supportability improvements:
* Custom (basic) error page
* All HTTP errors are now logged as warnings
* It's now possible to do a GET on for instance /activitycategories/, to see whether the service is up.

YD-148 Improve error reporting

---

appservice/src/main/resources/static/swagger/swagger-spec.yaml

* PUT on /users/{id} actually returns a UserWithPrivateData, not a PostPutUser as used to be in the spec.
* DELETE on /users/{id} takes a message query parameter
* We were not consistent in the way we specify IDs. E.g. we use /users/{id}} and /users/{userID}/messages/.

YD-247 inconsistencies in swagger spec

---

appservice/src/intTest/groovy/nu/yona/server/RemoveUserTest.groovy
core/src/main/java/nu/yona/server/messaging/entities/MessageDestination.java
core/src/testUtils/groovy/nu/yona/server/test/AppService.groovy

* Extended the test to reproduce the scenario
* Changed the order of the equals operation in MessageDestination.removeMessagesFromUser

YD-249 Remove user failed

---

appservice/src/intTest/groovy/nu/yona/server/CreateUserOnBuddyRequestTest.groovy
core/src/main/java/nu/yona/server/analysis/entities/DayActivityRepository.java
core/src/main/java/nu/yona/server/messaging/entities/MessageDestination.java
core/src/main/java/nu/yona/server/subscriptions/service/UserService.java
core/src/testUtils/groovy/nu/yona/server/test/AppService.groovy

* Cascading delete does not work when deleting through a JQL statement, so day activities are to be deleted explicitly.
* We removed the messages from the destination, but orphan removal was off, so the messages continued to exist, thus prohibiting removal of the goal linked to a goal change message.
There is still one more such issue, see YD-261.

YD-244 Delete user with activities fails

---

core/src/testUtils/groovy/nu/yona/server/YonaServer.groovy

Now it prints this for the Sunday - Saturday past week:
2016-05-29T05:00+02:00[Europe/Amsterdam]
2016-05-30T05:00+02:00[Europe/Amsterdam]
2016-05-31T05:00+02:00[Europe/Amsterdam]
2016-06-01T05:00+02:00[Europe/Amsterdam]
2016-06-02T05:00+02:00[Europe/Amsterdam]
2016-06-03T05:00+02:00[Europe/Amsterdam]
2016-06-04T05:00+02:00[Europe/Amsterdam]

YD-259 Corrected the day handling.

---

appservice/src/intTest/groovy/nu/yona/server/AbstractAppServiceIntegrationTest.groovy
appservice/src/intTest/groovy/nu/yona/server/ActivityTest.groovy
appservice/src/main/java/nu/yona/server/goals/rest/GoalController.java
appservice/src/main/java/nu/yona/server/subscriptions/rest/PinResetRequestController.java
core/src/main/java/nu/yona/server/analysis/service/ActivityService.java
core/src/main/java/nu/yona/server/analysis/service/AnalysisEngineService.java
core/src/main/java/nu/yona/server/goals/service/BudgetGoalDTO.java
core/src/main/java/nu/yona/server/goals/service/GoalDTO.java
core/src/main/java/nu/yona/server/goals/service/GoalService.java
core/src/main/java/nu/yona/server/goals/service/TimeZoneGoalDTO.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyService.java
core/src/main/java/nu/yona/server/subscriptions/service/PinResetRequestService.java
core/src/main/java/nu/yona/server/subscriptions/service/UserAnonymizedDTO.java
core/src/main/java/nu/yona/server/subscriptions/service/UserDTO.java
core/src/main/java/nu/yona/server/subscriptions/service/UserService.java
core/src/test/java/nu/yona/server/analysis/service/ActivityServiceTests.java
core/src/test/java/nu/yona/server/analysis/service/AnalysisEngineServiceTests.java

instead of goal entities
Along with this, the following is done:
* Add a test that failed before the fix (failed to lazily initialize a collection)
* Renamed GoalService.getGoal into getGoalForUserID and added getGoalForUserAnonymizedID
* Renamed UserService.getUserByID into getUserEntityByID, in alignment with other get...Entity methods
* Extended GoalService with operations to deal with user anonymized

YD-263 Cache goal DTOs inside UserAnonymizedDTO

---

appservice/src/intTest/groovy/nu/yona/server/ActivityTest.groovy
core/src/main/java/nu/yona/server/analysis/entities/DayActivityRepository.java
core/src/main/java/nu/yona/server/analysis/entities/WeekActivityRepository.java
core/src/main/java/nu/yona/server/goals/service/GoalService.java

The test is very basic and needs to be extended, but it proves the basics: the related activity entries are removed.

YD-274 Remove activities along with goals

---

appservice/src/intTest/groovy/nu/yona/server/AppActivityTest.groovy
core/src/main/java/nu/yona/server/analysis/service/AnalysisEngineService.java
core/src/test/java/nu/yona/server/analysis/service/AnalysisEngineServiceTests.java

Can you have a look at this?
To my surprise, I have one failing test: ActivityTest."Add activity after retrieving the report with multiple days"
```
Condition not satisfied:
dayActivityOverview.dayActivities?.size() == expectedValues[shortDay].size()
|                   |              |      |  |             ||         |
|                   |              2      |  |             |Wed       1
|                   |                     |  |             [[goal:nu.yona.server.test.BudgetGoal@4295f2a0, data:[goalAccomplished:true, minutesBeyondGoal:0, spread:[]]]]
|                   |                     |  [Mon:[[goal:nu.yona.server.test.BudgetGoal@4295f2a0, data:[goalAccomplished:true, minutesBeyondGoal:0, spread:[]]]], Tue:[[goal:nu.yona.server.test.BudgetGoal@4295f2a0, …
```

YD-309 Now ignores activities occuring before the goal creation time

---

appservice/src/intTest/groovy/nu/yona/server/AppActivityTest.groovy
core/src/main/java/nu/yona/server/analysis/service/AnalysisEngineService.java
core/src/main/java/nu/yona/server/exceptions/AnalysisException.java
core/src/main/resources/messages/messages.properties
core/src/main/resources/messages/messages_nl.properties

* Start time must be before end type
* Start time and end time cannot be in the future
Added tests. Made explicit that we accept a 10 second deviation between the app and the server time.

YD-309 Added app activity validations

---

core/src/main/java/nu/yona/server/goals/entities/TimeZoneGoal.java

For a time zone goal, the time beyond the goal is calculated by summing the conflicting spread cells. Due to rounding, that sum might be more than the total time spent. This is confusing, so it's corrected now.

YD-313 fixed inconsistency in totals

---

appservice/src/intTest/groovy/nu/yona/server/ActivityTest.groovy
appservice/src/intTest/groovy/nu/yona/server/BasicBuddyTest.groovy
appservice/src/intTest/groovy/nu/yona/server/DisclosureTest.groovy
appservice/src/intTest/groovy/nu/yona/server/EditGoalsTest.groovy
appservice/src/main/java/nu/yona/server/analysis/rest/ActivityControllerBase.java
appservice/src/main/java/nu/yona/server/analysis/rest/UserActivityController.java
appservice/src/main/java/nu/yona/server/messaging/rest/MessageController.java
appservice/src/main/java/nu/yona/server/subscriptions/rest/BuddyController.java
appservice/src/main/java/nu/yona/server/subscriptions/rest/UserController.java
appservice/src/main/resources/static/swagger/swagger-spec.yaml
core/src/main/java/nu/yona/server/analysis/service/ActivityCommentMessageDTO.java
core/src/main/java/nu/yona/server/analysis/service/GoalConflictMessageDTO.java
core/src/main/java/nu/yona/server/goals/service/GoalChangeMessageDTO.java
core/src/main/java/nu/yona/server/messaging/entities/DisclosureRequestMessage.java
core/src/main/java/nu/yona/server/messaging/entities/DisclosureResponseMessage.java
core/src/main/java/nu/yona/server/messaging/service/BuddyMessageDTO.java
core/src/main/java/nu/yona/server/messaging/service/BuddyMessageEmbeddedUserDTO.java
core/src/main/java/nu/yona/server/messaging/service/BuddyMessageLinkedUserDTO.java
core/src/main/java/nu/yona/server/messaging/service/DisclosureRequestMessageDTO.java
core/src/main/java/nu/yona/server/messaging/service/DisclosureResponseMessageDTO.java
core/src/main/java/nu/yona/server/messaging/service/MessageDTO.java
core/src/main/java/nu/yona/server/messaging/service/MessageService.java
core/src/main/java/nu/yona/server/messaging/service/SenderInfo.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyConnectRequestMessageDTO.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyConnectResponseMessageDTO.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyService.java
core/src/main/java/nu/yona/server/subscriptions/service/UserService.java
core/src/testUtils/groovy/nu/yona/server/test/AppService.groovy

- Added following links:
1.disclose request message: link of  URL from  day activity detail of myself 
2.disclose response message: link of URL from  day activity detail of  buddy (if disclosed)
3.buddy connect response message: link to  buddy URL in user
4.goal change message: link to URL of day activity overview of buddy
- Refactored sender structure (made it more consistent)
- Using <self> in activity comment message instead of nickname for consistency

YD-337 Add notification links

---

analysisservice/src/main/java/nu/yona/server/AnalysisServiceApplication.java
analysisservice/src/main/java/nu/yona/server/analysis/service/AnalysisEngineService.java
analysisservice/src/main/java/nu/yona/server/analysis/service/InactivityManagementService.java
analysisservice/src/test/java/nu/yona/server/analysis/service/AnalysisEngineServiceTests.java
core/src/main/java/nu/yona/server/util/LockPool.java
core/src/test/java/nu/yona/server/util/LockPoolTest.java

* Renamed UserAnonymizedSynchronizer into LockPool
* Moved it into nu.yona.util, inside Core
* Made it generic, with the ID type as type parameter
* Added a unit test that verifies:
* Nonconcurrency when using the lock in a nonreentrant way
* Nonconcurrency when using the lock in a reentrant way
* Immediate access when using different keys

YD-370 Generalized LockPool and added unit test

---

adminservice/src/main/java/nu/yona/server/goals/rest/ActivityCategoryController.java
analysisservice/src/main/java/nu/yona/server/analysis/service/ActivityCacheService.java
core/src/main/java/nu/yona/server/goals/entities/ActivityCategory.java
core/src/main/java/nu/yona/server/goals/entities/ActivityCategoryRepository.java
core/src/main/java/nu/yona/server/goals/service/ActivityCategoryService.java
core/src/test/java/nu/yona/server/goals/service/ActivityCategoryServiceIntegrationTest.java
core/src/test/java/nu/yona/server/goals/service/ActivityCategoryServiceTest.java
core/src/test/java/nu/yona/server/goals/service/ActivityCategoryServiceTestBase.java
dbinit/data/productionActivityCategories.json
dbinit/src/main/java/nu/yona/server/dbinit/ActivityCategoryFileLoader.java

* Implemented a PUT option on ``/activityCategories/``. This allows setting the production activity categories through a command like this: ``curl -X PUT http://localhost:8080/activityCategories/ -d @dbinit/data/productionActivityCategories.json --header "Content-Type: application/json"``
* There is an issue in HSQLDB, Spring or JPA that makes an implicit flush fail with ``java.sql.SQLException: invalid transaction state: read-only SQL-transaction``. Implemented an explicit flush to work around that issue.
* Added an extra JSON file with the production activity categories
* Removed  ``Games`` from the activity categories file used for testing
* Reformatted the activity categories in the JSON file, to increase readability and simplify comparison
* Renamed local variable in …

YD-373 Implemented PUT for all act cats

---

analysisservice/src/main/java/nu/yona/server/analysis/service/AnalysisEngineService.java
analysisservice/src/test/java/nu/yona/server/analysis/service/ActivityServiceTests.java
appservice/src/intTest/groovy/nu/yona/server/AddDeviceTest.groovy
appservice/src/intTest/groovy/nu/yona/server/BasicBuddyTest.groovy
appservice/src/intTest/groovy/nu/yona/server/MessagingTest.groovy
appservice/src/intTest/groovy/nu/yona/server/OverwriteUserTest.groovy
appservice/src/intTest/groovy/nu/yona/server/RemoveUserTest.groovy
appservice/src/intTest/groovy/nu/yona/server/UserTest.groovy
core/src/main/java/nu/yona/server/subscriptions/service/BuddyService.java
core/src/main/java/nu/yona/server/subscriptions/service/UserService.java
core/src/testUtils/groovy/nu/yona/server/test/AppService.groovy

The solution comprises of the following as part of ``UserService.deleteUser``:
* Process any pending buddy response messages, to ensure a standard state
* Handle buddy users removed while offline
* When handling buddy users removed while offline, also remove the messages sent by this user to the user that was removed while offline
Besides this:
* Fixed DST issues
* Added missing clean-ups

YD-261 Fixed delete failure after user overwrite

---

appservice/src/intTest/groovy/nu/yona/server/BasicBuddyTest.groovy
appservice/src/main/java/nu/yona/server/subscriptions/rest/BuddyController.java
appservice/src/main/resources/static/swagger/swagger-spec.yaml
core/src/main/java/nu/yona/server/messaging/entities/MessageDestination.java
core/src/main/java/nu/yona/server/messaging/entities/MessageRepository.java
core/src/main/java/nu/yona/server/messaging/entities/MessageSource.java
core/src/main/java/nu/yona/server/messaging/service/MessageService.java
core/src/main/java/nu/yona/server/subscriptions/entities/Buddy.java
core/src/main/java/nu/yona/server/subscriptions/entities/BuddyAnonymized.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyDTO.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyService.java
core/src/testUtils/groovy/nu/yona/server/test/Buddy.groovy
dbinit/liquibase.gradle
dbinit/src/main/liquibase/base/entity.yml
dbinit/src/main/liquibase/changelog.yml
dbinit/src/main/liquibase/updates/changelog-0000-yd-227.yml
dbinit/src/main/liquibase/updates/updates.yml

Added lastStatusChangeTime to BuddyAnonymized. It is updated when the buddy request is created, accepted, rejected or disconnected.
As this is the first change that requires a schema change, several other changes are included:
* Introduction of updates.yml, the file accumulating includes for all schema changes
* Corrected destination path in liquibase.gradle in task liquibaseDiffChangelog
* Removed the devices table from entity.yml. This shouldn't have been there as the Device class was removed already as part of PR #267. This was missed when merging these changes into the work for the Liquibase introduction.
Unfortunately, we always need to update the generated change log manually due to liquibase/liquibase-hibernate#134. This is included in the wiki procedure: …

YD-227 Time stamp on BuddyAnonymized

---

adminservice/src/main/java/nu/yona/server/AdminServiceApplication.java
analysisservice/src/main/java/nu/yona/server/AnalysisServiceApplication.java
appservice/src/main/java/nu/yona/server/AppServiceApplication.java
batchservice/src/main/java/nu/yona/server/BatchServiceApplication.java
core/src/main/java/nu/yona/server/CoreConfiguration.java
dbinit/src/main/java/nu/yona/server/DatabaseInitializationApplication.java

As pointed out by @wilkinsona on spring-projects/spring-boot#7418, our Hazelcast initialization was wrong. Spring couldn't see the Hazelcast bean and therefore couldn't shut it down. Corrected that now.

YD-382 Simplify Hazelcast shutdown

---

appservice/src/intTest/groovy/nu/yona/server/AbstractAppServiceIntegrationTest.groovy
appservice/src/intTest/groovy/nu/yona/server/CreateUserOnBuddyRequestTest.groovy
appservice/src/intTest/groovy/nu/yona/server/RemoveUserTest.groovy
appservice/src/intTest/groovy/nu/yona/server/UpdateBuddyUserInfoTest.groovy
appservice/src/main/java/nu/yona/server/subscriptions/rest/UserController.java
appservice/src/main/resources/static/swagger/swagger-spec.yaml
core/src/main/java/nu/yona/server/crypto/CryptoSession.java
core/src/main/java/nu/yona/server/crypto/CryptoUtil.java
core/src/main/java/nu/yona/server/crypto/PublicKeyEncryptor.java
core/src/main/java/nu/yona/server/subscriptions/service/UserDto.java
core/src/main/java/nu/yona/server/subscriptions/service/UserPrivateDto.java
core/src/testUtils/groovy/nu/yona/server/test/AppService.groovy
core/src/testUtils/groovy/nu/yona/server/test/User.groovy

The app can still provide the password upon user sign-up, but this is only temporary. Once both app implementations are updated, this will be disabled.
The Yona password is now returned as part of the private user data. This happens when signing up, but also in other scenarios where the private user data is returned (e.g. GET on user). The app should take the password as returned in the user data and use that in subsequent requests.
Changes:
* Added yonaPassword to the Swagger spec
* Included it in the UserPrivateDto
* Rearranged some crypto-related code
* Made UserController.addUser generate the key if the Yona-Password header was not provided
* Updated the Groovy tests. Most tests now use the server-generated password. Some tests still generated it in the client, which is good for …

YD-397 Moved password generation to the server

---

core/src/main/java/nu/yona/server/properties/YonaProperties.java
core/src/main/java/nu/yona/server/subscriptions/service/UserService.java
core/src/main/java/nu/yona/server/subscriptions/service/UserServiceException.java
core/src/main/resources/messages/messages.properties
core/src/main/resources/messages/messages_nl.properties

It's done through a configuration property. This requires the service to be restarted when the maximum is updated. Given that this is a temporary feature and restarting is fast, this shouldn't be a problem.

YD-401 Limit the number of users

---

adminservice/src/main/java/nu/yona/server/admin/DashboardController.java

In an attempt to prevent the below error:
```
Query is : set autocommit=0
org.springframework.transaction.CannotCreateTransactionException: Could not open JDBC Connection for transaction; nested exception is java.sql.SQLNonTransientConnectionException: (conn:42) Could not read resultset: unexpected end of stream, read 0 bytes from 4
Query is : set autocommit=0
at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:242) ~[spring-jdbc-4.0.6.RELEASE.jar!/:4.0.6.RELEASE]
at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373) ~[spring-tx-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactio …
```

YD-378 Marked the controller method as transactional

---

adminservice/src/main/java/nu/yona/server/admin/DashboardController.java
adminservice/src/main/resources/templates/dashboard.html
core/src/main/resources/application.properties

* Swapped the query parameters of the between. Between <high> and <low> does not return anything.
* Put the user count in the tool tip.
* Made the right side margin a little wider. The label for the right-side column sometimes didn't render.
I couldn't figure out why the JDBC connection is often closed when the admin service runs in the production environment.

YD-412 Dashboard improvements

---

appservice/src/intTest/groovy/nu/yona/server/EditGoalsTest.groovy
core/src/main/java/nu/yona/server/analysis/entities/WeekActivity.java
core/src/main/java/nu/yona/server/goals/service/GoalService.java

The cause was that upon a goal change, we create a copy of the goal, but both copies had the same start time. The history item should carry the original creation time, but the "actual" goal should have its creation time updated to the current time. Once the data is corrected, the "week already full" issue will disappear. The fix of this change set will prevent from creating the wrong data again.

YD-411 Fixed week already full error

---

scripts/servers_debug.cmd
scripts/servers_start.cmd

Improved the test run script in the following ways:
* Now doesn't run Gradle in parallel anymore. This addresses the random class loading error and makes the service start up faster
* Now automatically starts the tests when all services are up and running (no need to hit enter anymore)
* Gives a more clear error message when something fails
Note that this requires curl 7.51.1 or later, as we use curl/curl#1064

YD-413 Improved start script

---

appservice/src/intTest/groovy/nu/yona/server/PinResetRequestTest.groovy
batchservice/src/main/java/nu/yona/server/batch/service/BatchTaskService.java

Added the current date/time as a uniqueInstanceId job parameter. That way, it can be run repeatedly.

YD-418 Fixed "job instance already exists"

---

appservice/src/intTest/groovy/nu/yona/server/PinResetRequestTest.groovy
core/src/main/java/nu/yona/server/batch/client/PinResetConfirmationCodeSendRequestDto.java

Cause: Use of ``ISO_DATE_PATTERN`` for the ``executionTime`` property of ``PinResetConfirmationCodeSendRequestDto`` instead of ``ISO_DATE_TIME_PATTERN``
This was going unnoticed because the test "Hacking attempt: Try to verify pin reset confirmation code before end of delay period" was checking the PIN too early, before the batch job had a chance to generate it. Now it's tested in the middle of the interval. That failed with the old bug but passes now.

YD-423 PIN reset code was sent too early

---

appservice/src/intTest/groovy/nu/yona/server/BasicBuddyTest.groovy
appservice/src/intTest/groovy/nu/yona/server/CreateUserOnBuddyRequestTest.groovy
appservice/src/intTest/groovy/nu/yona/server/MessagingTest.groovy
appservice/src/intTest/groovy/nu/yona/server/OverwriteUserTest.groovy
appservice/src/intTest/groovy/nu/yona/server/RejectBuddyTest.groovy
appservice/src/intTest/groovy/nu/yona/server/RemoveUserTest.groovy
appservice/src/intTest/groovy/nu/yona/server/UpdateBuddyUserInfoTest.groovy
appservice/src/main/java/nu/yona/server/messaging/rest/MessageController.java
core/src/main/java/nu/yona/server/messaging/entities/MessageRepository.java
core/src/main/java/nu/yona/server/messaging/service/MessageDto.java
core/src/main/java/nu/yona/server/messaging/service/MessageService.java
core/src/testUtils/groovy/nu/yona/server/test/AppService.groovy
scripts/servers_start.cmd

At the time messages are fetched, we now first check whether any messages need to be processed. If so, we do that before returning the messages. As a result, clients never need to trigger processing anymore. This prevents the issue that the first message cannot be interpreted because the second message hasn't been processed yet (the issue causing YD-419).

YD-419 Messages are now automatically processed

---

appservice/src/intTest/groovy/nu/yona/server/ActivityAggregationBatchJobTest.groovy
batchservice/src/main/java/nu/yona/server/batch/jobs/ActivityAggregationBatchJob.java
core/src/main/java/nu/yona/server/analysis/entities/DayActivity.java
core/src/main/java/nu/yona/server/analysis/entities/DayActivityRepository.java
core/src/main/java/nu/yona/server/analysis/entities/WeekActivity.java
core/src/main/java/nu/yona/server/analysis/entities/WeekActivityRepository.java

* Using the ``JpaPagingItemReader`` leads to skipped entities, see http://stackoverflow.com/questions/26509971/spring-batch-jpapagingitemreader-why-some-rows-are-not-read. Now we use ``JdbcPagingItemReader`` instead
* Increased the chunk sizes from 10 to 200. This improved the day activity performance from 67 seconds to 14 and the week activity performance from 33 to 5 in my test run.
* Corrected the CRUD repositories for ``DayActivity`` and ``WeekActivity``. They still used UUID while the ID was already switched to long.
* Corrected a test in ``ActivityAggregationBatch``. The original values were based on the wrong behavior and the fact that the tests were run on Tuesday :)

YD-162 Process all eligible activities

---

analysisservice/src/main/java/nu/yona/server/analysis/service/AnalysisEngineService.java
core/src/main/java/nu/yona/server/exceptions/AnalysisException.java
core/src/main/resources/messages/messages.properties
core/src/main/resources/messages/messages_nl.properties

If the problem occurs again, we now explicitly throw an exception that carries information to analyze the issue.
Note that the issue is not fixed yet, but given we can't reproduce it, this is the best we can do.

YD-430 Improved error handling

---

core/src/main/resources/messages/messages.properties

Old: Cannot someone who is already a buddy
New: Cannot invite someone who is already a buddy

YD-445 Corrected error message

---

appservice/src/intTest/groovy/nu/yona/server/EditGoalsTest.groovy
core/src/main/java/nu/yona/server/goals/service/GoalService.java
core/src/main/java/nu/yona/server/messaging/service/MessageService.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyService.java
core/src/main/java/nu/yona/server/subscriptions/service/UserAnonymizedDto.java

This sequence went wrong:
* Buddy disconnected
* User removed goal
While this one was successful:
* Buddy disconnected
* User retrieved messages (and along with that processed buddy disconnects)
* User removed goal
This is now fixed and a test case is added.

YD-443 Fixed IllegalStateException

---

core/src/main/java/nu/yona/server/analysis/entities/DayActivity.java
core/src/main/java/nu/yona/server/analysis/entities/WeekActivity.java

This reduces the amount of select queries to only one per type instead
of one per day activity in the week overview

YD-456 Using a proper batch size for activity fetching

---

appservice/src/intTest/groovy/nu/yona/server/UserTest.groovy
appservice/src/main/java/nu/yona/server/subscriptions/rest/UserController.java
appservice/src/main/resources/static/swagger/swagger-spec.yaml
core/src/testUtils/groovy/nu/yona/server/test/User.groovy

To work around the issue that the iOS app currently does not support binary responses (which occur when the mobile config is signed).

YD-464 Added base-64 encoded Mobile Config

---

appservice/build.gradle
appservice/src/intTest/groovy/nu/yona/server/AbstractAppServiceIntegrationTest.groovy
appservice/src/intTest/groovy/nu/yona/server/ActivityAggregationBatchJobTest.groovy
appservice/src/intTest/groovy/nu/yona/server/ActivityCommentTest.groovy
appservice/src/intTest/groovy/nu/yona/server/PerformanceSetupTest.groovy
build.gradle
dbinit/data/activityCategories.json

The test creates:
* A user with 3 buddies
* Each of the 4 users gets 4 goals, three budget goals and a timezone goal
* Two if the timezone goals are updated 3 times, to create history items
* Over a period of the current week and the two preceding weeks, each user does 4 activities for each goal, in the early hours of the day
* The "main user" and one of his buddies is having a conversation (multiple activity comment messages) on an activity of yesterday
As the test is rather time consuming (2.5 minutes), it is skipped by default. To run it, do this:
```
gradlew :appservice:cleanIntTest :appservice:intTest -Pyona_test_gen_data=true -DintTest.single=PerformanceSetupTest
```
The user and his password are printed to stdout, like this (in the test output):
```
Test user URL: …
```

YD-461 Test to generate data for query analysis

---

core/build.gradle
core/src/main/java/nu/yona/server/properties/SmsProperties.java
core/src/main/java/nu/yona/server/sms/PlivoSmsService.java
core/src/main/resources/application.properties
core/src/test/java/nu/yona/server/sms/PlivoSmsServiceTest.java
k8s/helm/yona-server/templates/01_configmap_properties.yaml
k8s/helm/yona-server/values.yaml

New properties are introduced:
yona.sms.defaultSenderNumber = +17184169858
yona.sms.alphaSenderId = Yona
yona.sms.alphaSenderSupportingCountryCallingCodes = +31 +49 +33
If the country calling code of the target phone number is in the alpha-sender-supporting country calling codes, then the alphaSenderId will be used as sender, otherwise the defaultSenderNumber.

YD-468 Support different SMS sender numbers

---

k8s/helm/yona/templates/10_deployment_admin.yaml
k8s/helm/yona/templates/10_deployment_app.yaml

When running on a local development standup, using no external load balancer, the pods communicate directly against the defined service IPs - This also means they need to talk to the exposed ports.  Either direct againt 8080 for springboot apps, or perhaps against defined node ports.   Not going through the kube-proxy (used in node ports) is more efficient, so I just added :8080 to the default urls.
```
app# curl http://analysis.yona.svc.cluster.local     
curl: (7) Failed to connect to analysis.yona.svc.cluster.local port 80: Network is unreachable
```
vs...
```
app# curl http://analysis.yona.svc.cluster.local:8080     
{
"timestamp" : "2017-06-21T18:11:44.640+0000",
"status" : 404,
"error" : "Not Found",
"message" : "No message available",
"path" : "/"
}
```

Fix the URL endpoints for internal communication for dev standup

---

k8s/helm/yona/Chart.yaml
k8s/helm/yona/templates/01_configmap_properties.yaml

go template 'default' function seems to feel that false values = nill/empty/undef values.
As a result, any value we set to 'false' would always get the default value.
I added a 'required' function in place.  This seems to have no issue understanding false != undef, and provides an indication to developer that this is a required field, if they have somehow missed it in values.yaml.  An alternative would have been to implement some conditionals, but messy imho.
Validation/Test case for fix : 
```
yona.email.enabled=true
yona.email.enabled=false
```

Work around go template or helm yaml poor default handling for booleans

---

appservice/src/intTest/groovy/nu/yona/server/MessagingTest.groovy
build.gradle

This fixes the performance issue
[https://github.com/spring-projects/spring-hateoas/issues/525], which
was solved in Spring Framework 4.3.5.
Edited the single broken test. It seems PagedResourceAssembler adds a
different self link in case no paging was passed, but I don't think that
is harmful.

YD-473 Upgrade to Spring Boot 1.4.7

---

README.md
core/src/main/java/nu/yona/server/subscriptions/entities/Buddy.java
core/src/main/java/nu/yona/server/subscriptions/entities/BuddyAnonymized.java
core/src/main/java/nu/yona/server/subscriptions/entities/UserAnonymized.java

Rather than a UUID, to create a regular and clean JPA model.
Along with this added extra assert to Buddy.java

YD-476 Define BuddyAnonymized.owningUserAnonymized as entity

---

analysisservice/src/main/java/nu/yona/server/analysis/service/AnalysisEngineService.java
analysisservice/src/test/java/nu/yona/server/analysis/service/AnalysisEngineServiceTest.java

The analysis engine scales each activity up to at least one minute. So this is what could happen:
* User opens app for 20 seconds
* Analysis engine scales this up to 1 minute
* In 20 seconds, the user opens the app again, now for 3 minutes
This should result in an activity of 3 minutes and 40 seconds. In the past, a new activity was created, because start time of the new activity was not equal to the end time of the previous one. Now a new activity is created when the start time is after the end time of the last activity, not when it is equal or before it.

YD-408 Overlapping activity is merged

---

appservice/src/main/java/nu/yona/server/analysis/rest/AppActivityController.java
core/src/main/java/nu/yona/server/properties/AnalysisServiceProperties.java
core/src/main/resources/application.properties

When a user posts more app activities than the configured threshold, the set of app activities is ignored. This is a workaround for APPDEV-1022: the app accumulates all app activities and posts all historical app activities along with each new one, thus accumulating collections of app activities as large as 745,846 items. By ignoring large sets in the app service, the analysis engine service doesn't get overloaded. Once the issue in the app is fixed, we can remove these provisions again.

YD-485 Ignore too large sets of app activities

---

core/src/main/java/nu/yona/server/sms/PlivoSmsService.java

When the response from Plivo contains "is not a valid phone number", we will now return an appropriate error message to the user instead of a technical one.

YD-488 Appropriate error code on invalid number

---

appservice/src/intTest/groovy/nu/yona/server/AbstractAppServiceIntegrationTest.groovy
appservice/src/intTest/groovy/nu/yona/server/AddDeviceTest.groovy
appservice/src/intTest/groovy/nu/yona/server/BuddyValidationTest.groovy
appservice/src/intTest/groovy/nu/yona/server/CreateUserOnBuddyRequestTest.groovy
appservice/src/intTest/groovy/nu/yona/server/HibernateStatsTest.groovy
appservice/src/intTest/groovy/nu/yona/server/OverwriteUserTest.groovy
appservice/src/intTest/groovy/nu/yona/server/UserTest.groovy
appservice/src/intTest/groovy/nu/yona/server/UserValidationTest.groovy
core/build.gradle
core/src/main/java/nu/yona/server/exceptions/InvalidDataException.java
core/src/main/java/nu/yona/server/subscriptions/service/UserService.java
core/src/main/resources/messages/messages.properties
core/src/main/resources/messages/messages_nl.properties

Added a dependency on Google's libphonenumber to verify the numbers. Only numbers of the types MOBILE and FIXED_LINE_OR_MOBILE are accepted. The tests are updated to produce numbers that match Google's definition of mobile numbers.
Extended UserValidationTest with a test that verifies that fixed line numbers are rejected.

YD-493 Block all nonmobile numbers

---

core/src/main/resources/application.properties
core/src/main/resources/templates/email/buddy-invitation-body.html
core/src/main/resources/templates/email/messages.properties
core/src/main/resources/templates/email/messages_nl.properties

As the app is still in closed beta. Next, corrected the instructions. There used to be a step that said you should first join in the app and then open the URL, but that was wrong. You should after installation immediately open the URL that was provided in the mail.
Once we end closed beta, we should update application.properties and set this property:
yona.email.googlePlayStoreUrl=https://play.google.com/store/apps/details?id=nu.yona.app

YD-502 Now use Google Play testing link

---

core/src/main/java/nu/yona/server/subscriptions/entities/BuddyConnectMessage.java
core/src/main/java/nu/yona/server/subscriptions/service/UserService.java

It resulted in an empty string that we tried to parse as a UUID.
Along with this, fixed a minor SonarQube complaint

YD-508 Fixed exception on empty device list in buddy request

---

analysisservice/src/main/java/nu/yona/server/analysis/service/AnalysisEngineService.java
analysisservice/src/test/java/nu/yona/server/analysis/service/AnalysisEngineServiceTest.java
core/src/main/java/nu/yona/server/analysis/service/NetworkActivityDto.java

If the user has an "old account", without device and they did not open the Yona app yet after the migration step to add a device was introduced, they still do not have a device. In such a scenario, we now ignore the app activities till they opened the app and with that got a device registered.
Along with this addressed an issue with the default value of the device index in the NetworkActivityDto.

YD-523 Ignore network activity if app not opened

---

appservice/src/main/java/nu/yona/server/subscriptions/rest/UserController.java
core/src/main/java/nu/yona/server/analysis/entities/Activity.java
core/src/main/java/nu/yona/server/analysis/entities/ActivityRepository.java
core/src/main/java/nu/yona/server/device/service/DeviceService.java
core/src/main/java/nu/yona/server/subscriptions/entities/User.java
core/src/main/java/nu/yona/server/subscriptions/entities/UserLockChecker.java
core/src/main/java/nu/yona/server/subscriptions/entities/UserRepository.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyService.java
core/src/main/java/nu/yona/server/subscriptions/service/NewDeviceRequestService.java
core/src/main/java/nu/yona/server/subscriptions/service/PinResetRequestService.java
core/src/main/java/nu/yona/server/subscriptions/service/UserDto.java
core/src/main/java/nu/yona/server/subscriptions/service/UserService.java
core/src/test/java/nu/yona/server/device/service/DeviceServiceTest.java
core/src/test/java/nu/yona/server/entities/ActivityRepositoryMock.java
core/src/test/java/nu/yona/server/entities/MockCrudRepositoryEntityWithId.java
core/src/test/java/nu/yona/server/entities/UserRepositoryMock.java
core/src/test/java/nu/yona/server/subscriptions/service/UserServiceTest.java

All updates to the User entity are now done while owning a pessimistic lock database lock. This lead to some deadlocks where updates happened in different transactions on the same thread. These issues have been resolved through changes in the exception-based rollback.

YD-524 Correct user entity locking and remove superfluous devices

---

appservice/src/main/java/nu/yona/server/subscriptions/rest/NewDeviceRequestController.java
core/src/main/java/nu/yona/server/crypto/seckey/CryptoSession.java
core/src/main/java/nu/yona/server/subscriptions/entities/User.java
core/src/main/java/nu/yona/server/subscriptions/service/UserService.java
core/src/test/java/nu/yona/server/subscriptions/service/PrivateUserDataMigrationServiceIntegrationTest.java

The result of the data migration was not stored in the user anonymized cache.
Now every update to a user also updates the user anonymized cache, provided the update is done in a context where the user private data can be accessed.

YD-529 Fix "No devices" error

---

adminservice/src/main/resources/messages/messages.properties
core/src/main/java/nu/yona/server/subscriptions/service/WhiteListedNumberService.java
core/src/main/java/nu/yona/server/subscriptions/service/WhiteListedNumberServiceException.java
core/src/main/resources/messages/messages.properties
core/src/main/resources/messages/messages_nl.properties

Removed messages.properties from admin service component, as it was hiding the common error messages resource in core.

YD-531 Fix error message for duplicate on white list

---

analysisservice/src/main/java/nu/yona/server/analysis/service/AnalysisEngineService.java
analysisservice/src/test/java/nu/yona/server/analysis/service/AnalysisEngineServiceTest.java
analysisservice/src/test/java/nu/yona/server/analysis/service/AnalysisEngineService_determineRelevantGoalsTest.java
appservice/src/intTest/groovy/nu/yona/server/AbstractAppServiceIntegrationTest.groovy
appservice/src/intTest/groovy/nu/yona/server/ActivityTest.groovy
appservice/src/intTest/groovy/nu/yona/server/BasicBuddyTest.groovy
appservice/src/intTest/groovy/nu/yona/server/DeviceTest.groovy
appservice/src/main/java/nu/yona/server/analysis/rest/UserActivityController.java
appservice/src/main/java/nu/yona/server/device/rest/DeviceController.java
core/src/main/java/nu/yona/server/crypto/seckey/CryptoSession.java
core/src/main/java/nu/yona/server/device/entities/DeviceAnonymized.java
core/src/main/java/nu/yona/server/device/service/DeviceService.java
core/src/main/java/nu/yona/server/device/service/DeviceServiceException.java
core/src/main/java/nu/yona/server/goals/service/GoalDto.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyService.java
core/src/main/java/nu/yona/server/subscriptions/service/NewDeviceRequestService.java
core/src/main/java/nu/yona/server/subscriptions/service/OwnUserPrivateDataDto.java
core/src/main/java/nu/yona/server/subscriptions/service/PinResetRequestService.java
core/src/main/resources/messages/messages.properties
core/src/main/resources/messages/messages_nl.properties
core/src/test/java/nu/yona/server/device/service/DeviceServiceTest.java
core/src/test/java/nu/yona/server/entities/UserRepositoryMock.java
core/src/test/java/nu/yona/server/subscriptions/service/PrivateUserDataMigrationServiceIntegrationTest.java
core/src/test/java/nu/yona/server/subscriptions/service/UserServiceTest.java
core/src/testUtils/groovy/nu/yona/server/test/CommonAssertions.groovy

* When a device of the type UNKNOWN registers app activities, it is autoclassified as Android (as today only Android is capable of registering app activities)
* Network activities for Android devices are ignored unless they relate to a no-go goal of the user

YD-517 Don't record time for network activities on Android devices

---

analysisservice/src/main/java/nu/yona/server/analysis/service/ActivityCacheService.java
appservice/src/intTest/groovy/nu/yona/server/ActivityTest.groovy

The ActivityCacheService didn't specify the device anonymized ID as part of the cache key. Due to that, activities of different devices were considered irrelevant because they overlapped.

YD-522 Fixed multidevice activity issue

---

scripts/smoothwall/HandleDansGuardianLog.pl

Earlier versions of Smoothwall placed the urlcategory under requesttags. The current version puts it under tagset. Updated the Perl script accordingly.

YD-540 New Smootwall places urlcategory differently

---

appservice/src/main/resources/static/swagger/swagger-spec.yaml

The definitions for ``UserPhotoLink`` and ``EditUserPhotoLink`` define the ``edit`` link instead of respectively ``yona:userPhoto`` and ``yona:editUserPhoto``.

YD-514 Corrected photo links

---

appservice/src/intTest/groovy/nu/yona/server/UserPhotoTest.groovy
core/src/main/java/nu/yona/server/subscriptions/service/UserDto.java

The UserDto class accidentally updated the user photo ID. This was wrong, as updating the user photo link is done differently.

YD-547 Fixed disappearing user photo link

---

Jenkinsfile
k8s/00_rbac-helm-config.yaml
k8s/02_storage.yaml
k8s/10_deployment_jnlp.yaml
k8s/helm/yona/Chart.yaml
k8s/helm/yona/requirements.yaml
k8s/helm/yona/templates/01_configmap_properties.yaml
k8s/helm/yona/templates/03_job-liquibase.yaml
k8s/helm/yona/templates/10_deployment_admin.yaml
k8s/helm/yona/templates/10_deployment_analysis.yaml
k8s/helm/yona/templates/10_deployment_app.yaml
k8s/helm/yona/templates/10_deployment_batch.yaml
k8s/helm/yona/values.yaml
k8s/hostpath_provisioner/01_provisioner-rbac.yaml
k8s/hostpath_provisioner/02_provisioner-deployment.yaml
k8s/hostpath_provisioner/03_provisioner-sc.yaml
k8s/hostpath_provisioner/README.md
scripts/wait-for-services.sh

- Added some new support files (helm rbac, jenkins slave example)
- Added new profile to wait-for-services script called k8snew.  This should work well with the new health checks and init containers in the pod specs.
- Containers are health checked against /health/ for the springboot containers.
- Containers are prefixed with an init container for DB and LDAP as needed (ldap only on liquibase for now)
- Changed the default storage handling to work faster and with less bootstrap code when using Minikube, and to use more common naming convention for other clusters.  Will still need to see how this impacts dev-build (might need to upgrade k8s there, and add a proper provisioner)
- Most dramatic change is the new values.yaml setup to break the ldap and db out from the Java URL references to …

Kti helm healthchecks

---

k8s/helm/yona/templates/10_deployment_admin.yaml
k8s/helm/yona/templates/10_deployment_analysis.yaml
k8s/helm/yona/templates/10_deployment_app.yaml
k8s/helm/yona/templates/10_deployment_batch.yaml
scripts/wait-for-services.sh

Due to changes that seem to affect us now at the beta 1.9.4 level of k8s, combined with new helm, we can no longer use the dynamic manifest labels because they are immutable now.  It makes logical sense, but it make for tracking a specific pod release when used with rolling upgrades harder.  We have to rely on the rolling upgrade system to keep track of that.
This restriction is not on the Job containers, and since that leads our process, we can still watch for that first in the wait-for-service checks.

K8S API Changes do not allow for mutable labels on containers

---

appservice/src/main/java/nu/yona/server/subscriptions/rest/BuddyController.java
appservice/src/main/java/nu/yona/server/subscriptions/rest/UserController.java

Due to issue spring-projects/spring-hateoas#703, the URL was encoded three times. A workaround is implemented now.

YD-551 Workaround for double encoding of invite URL

---

core/src/main/java/nu/yona/server/subscriptions/entities/User.java
core/src/main/java/nu/yona/server/subscriptions/entities/UserLockChecker.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyUserPrivateDataDto.java

This is fixed by making the UserLockChecker resilient for intermediate flushes.
Along with this, improved the logic in User and BuddyUserPrivateDataDto to fetch the user name from the user entity when that is not migrated yet.

YD-559 Fixed invalid lock mode error

---

README.md
core/src/main/java/nu/yona/server/subscriptions/entities/Buddy.java
core/src/main/java/nu/yona/server/subscriptions/entities/PrivateUserProperties.java
core/src/main/java/nu/yona/server/subscriptions/entities/UserPrivate.java
core/src/main/java/nu/yona/server/subscriptions/service/PrivateUserDataMigrationService.java
core/src/test/java/nu/yona/server/subscriptions/service/BuddyUserPrivateDataDtoTest.java
core/src/test/java/nu/yona/server/subscriptions/service/migration/EncryptFirstAndLastNameTest.java

The method to determine the name given some alternatives moved from BuddyConnectionChangeMessage to BuddyUserPrivateDataDtoTest, so a unit test was added for that.
* Moved the common properties of UserPrivate and Buddy to PrivateUserProperties
* Added a logging statement to PrivateUserDataMigrationService, so we can see when the migrations happened. If concurrent migrations happen (which I actually suspect), we get proof through the logging.

YD-558 Add unit test for BuddyUserPrivateDataDtoTest

---

core/build.gradle
core/src/main/java/nu/yona/server/CoreConfiguration.java
core/src/main/java/nu/yona/server/properties/YonaProperties.java
k8s/helm/yona/README.md
k8s/helm/yona/requirements.yaml
k8s/helm/yona/templates/01_configmap_properties.yaml
k8s/helm/yona/templates/03_job-liquibase.yaml
k8s/helm/yona/templates/10_deployment_admin.yaml
k8s/helm/yona/templates/10_deployment_analysis.yaml
k8s/helm/yona/templates/10_deployment_app.yaml
k8s/helm/yona/templates/10_deployment_batch.yaml
k8s/helm/yona/values.yaml

PR for the separation of Hazelcast out of the springboot and into a dedicated cluster.
To support local development a cluster will also be deployed via the Yona helm chart just like with MariaDB and LDAP if the infrastructure flag is enabled.

KTI_Hazelcast_Breakout

---

core/src/main/java/nu/yona/server/rest/GlobalExceptionMapping.java

* ``HttpMessageNotReadableException``
* ``HttpMediaTypeNotSupportedException``
(and ``MethodArgumentTypeMismatchException``, which was already in place)

YD-569 Return 500 on invalid requests

---

appservice/src/intTest/groovy/nu/yona/server/UpdateBuddyUserInfoTest.groovy
core/src/main/java/nu/yona/server/messaging/service/MessageService.java

The failure scenario is this:
* Richard sends a buddy request to Bob
* Bob accepts it and then changes his personal information
* Richard fetches his messages, which results in automatically processing all to-be-processed MessageService
* The first messages is the buddy acceptance; that succeeds and adds the user anonymized to the buddy
* Given that the user wasn't reloaded after the message was processed, the second one failed as it couldn't find the user anonymized ID on the buddy
The user is now fetched for each message. This will be a little slower when users have multiple messages to be processed, but this is extremely rare and thus not relevant. An integration test is added that reproduced the issue and now guards this scenario.

YD-570 Reload user after each message processing

---

core/src/main/java/nu/yona/server/messaging/entities/BuddyMessage.java
core/src/main/java/nu/yona/server/messaging/service/MessageDto.java
core/src/main/java/nu/yona/server/subscriptions/entities/Buddy.java
core/src/main/java/nu/yona/server/subscriptions/entities/BuddyConnectionChangeMessage.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyService.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyUserPrivateDataDto.java
core/src/test/java/nu/yona/server/messaging/entities/BuddyMessageTest.java
core/src/test/java/nu/yona/server/subscriptions/entities/BuddyTest.java
core/src/test/java/nu/yona/server/test/util/JUnitUtil.java

This scenario failed:
* The user A signed up for at 1 Mar 2018
* The user invited B to join Yona 4 minutes after sign-up
* User B didn't respond to the invitation
* At 14 May 2018, user B signed up for Yona, thus overwriting the account that was created on buddy request
* At 9 Jun 2018, user A opened Yona again, triggering the logic in handleBuddyUsersRemovedWhileOffline. At that time, user B was not migrated yet, so user A didn't have their first or last name in the buddy entity, causing an NPE
The fix is to use the logic of determineName to determine the first and last name that's included in the BuddyInfoParameters. To enable that, the method is moved from BuddyUserPrivateDataDto to Buddy.

YD-572 Fix NPE in BuddyMessage

---

appservice/src/intTest/groovy/nu/yona/server/ActivityCommentTest.groovy
appservice/src/main/java/nu/yona/server/goals/rest/GoalController.java
core/src/main/java/nu/yona/server/analysis/service/ActivityService.java
core/src/main/java/nu/yona/server/goals/service/GoalService.java
core/src/main/java/nu/yona/server/messaging/entities/MessageRepository.java
core/src/main/java/nu/yona/server/messaging/service/MessageService.java
core/src/main/java/nu/yona/server/subscriptions/service/UserService.java

This used to fail with a referential integrity error. This didn't fail when deleting a user. The fix is now to move the more elaborate message clean up of user deletion to the goal service, as part of the goal deletion.

YD-576 Allow deleting goal with activities with comments

---

core/src/main/java/nu/yona/server/analysis/service/ActivityCommentMessageDto.java
core/src/main/java/nu/yona/server/analysis/service/GoalConflictMessageDto.java
core/src/main/java/nu/yona/server/goals/service/GoalChangeMessageDto.java
core/src/main/java/nu/yona/server/messaging/service/DisclosureRequestMessageDto.java
core/src/main/java/nu/yona/server/messaging/service/DisclosureResponseMessageDto.java
core/src/main/java/nu/yona/server/messaging/service/MessageDto.java
core/src/main/java/nu/yona/server/messaging/service/SystemMessageDto.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyConnectRequestMessageDto.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyDisconnectMessageDto.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyInfoChangeMessageDto.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyService.java

Till now, DtoManager.handleAction was not marked with @transactional. Due to that, the services calls from implementations (also in subtypes) were individually starting a transaction, so the handling wasn't atomic. This is fixed now.
Along with this corrected the logging of buddy connect requests. The values "new" and "existing" were interchanged, so existing users where logged as new and vice versa.

YD-580 Message action handling now transactional

---

Jenkinsfile

Integration tests are hard coded IPs to the old build server.
Switched to DNS.   (DNS entry still points to old server as of this message for external queries, but is a localhost alias for the new build server)

Convert hard coded IPs in Jenkinsfile to DNS

---

core/src/main/java/nu/yona/server/exceptions/UpstreamException.java

If a remote call fails with e.g. a 503, then the caller will receive that status code.

YD-581 Return remote failure status code to caller

---

appservice/src/intTest/groovy/nu/yona/server/LocalizationTest.groovy
appservice/src/main/resources/static/swagger/swagger-spec.yaml
core/src/main/java/nu/yona/server/rest/ErrorLoggingFilter.java
core/src/main/java/nu/yona/server/rest/ErrorResponseDto.java
core/src/main/java/nu/yona/server/rest/GlobalExceptionMapping.java

This enables the app to include that in error reports that the users send to support, which in turn enables us to find the related log messages.

YD-582 Include correlation ID in error response

---

analysisservice/src/test/java/nu/yona/server/analysis/service/ActivityUpdateServiceTest.java
analysisservice/src/test/java/nu/yona/server/analysis/service/AnalysisEngineServiceTest.java
analysisservice/src/test/java/nu/yona/server/analysis/service/AnalysisEngineService_determineRelevantGoalsTest.java
appservice/src/intTest/groovy/nu/yona/server/DeviceManagementTest.groovy
appservice/src/intTest/groovy/nu/yona/server/DeviceTest.groovy
appservice/src/intTest/groovy/nu/yona/server/VpnConnectionStatusEventTest.groovy
appservice/src/main/java/nu/yona/server/device/rest/DeviceController.java
appservice/src/main/java/nu/yona/server/subscriptions/rest/UserController.java
appservice/src/main/resources/static/swagger/swagger-spec.yaml
core/src/main/java/nu/yona/server/device/entities/DeviceAnonymized.java
core/src/main/java/nu/yona/server/device/service/DeviceRegistrationRequestDto.java
core/src/main/java/nu/yona/server/device/service/DeviceService.java
core/src/main/java/nu/yona/server/device/service/DeviceUpdateRequestDto.java
core/src/main/java/nu/yona/server/device/service/UserDeviceDto.java
core/src/test/java/nu/yona/server/analysis/entities/ActivityTest.java
core/src/test/java/nu/yona/server/analysis/entities/IntervalActivityTestBase.java
core/src/test/java/nu/yona/server/analysis/service/ActivityServiceTest.java
core/src/test/java/nu/yona/server/device/service/DeviceServiceTest.java
core/src/test/java/nu/yona/server/subscriptions/service/BuddyDeviceChangeMessageDtoTest.java
core/src/test/java/nu/yona/server/subscriptions/service/migration/AddFirstDeviceTest.java
core/src/test/java/nu/yona/server/subscriptions/service/migration/MoveVpnPasswordToDeviceTest.java
core/src/testUtils/groovy/nu/yona/server/test/AppService.groovy
core/src/testUtils/groovy/nu/yona/server/test/Device.groovy
dbinit/src/main/liquibase/updates/changelog-0016-yd-549.yml
dbinit/src/main/liquibase/updates/updates.yml

- Support to pass the Firebase instance ID when registering a new device
- Support to set or update the Firebase instance ID of an existing device
- Returning the Firebase instance ID with the own user devices

YD-549 Support Firebase instance ID

---

k8s/helm/yona/values.yaml

Defining nodeport with anything fixes the parsing error on subvalues, even if that anything is nothing, as long as it exists. Alternate fix would be to not reference nested variables, e.g. change the structure from .Values.nodePorts.admin to .Values.nodeports-admin, since .Values always exists.

Defining variable

---

appservice/src/intTest/groovy/nu/yona/server/SystemMessageTest.groovy
batchservice/src/main/java/nu/yona/server/batch/quartz/jobs/EmailTestQuartzJob.java
core/src/main/java/nu/yona/server/email/EmailService.java
core/src/main/java/nu/yona/server/properties/EmailProperties.java
core/src/main/resources/application.properties
dbinit/data/QuartzOtherCronTriggers.json
dbinit/data/QuartzOtherJobs.json

* Made EmailService.prepareMimeMessage, as it shouldn't be used outside the service
* Enhanced SystemMessageTest.groovy to prevent intermittent failures due to timing

YD-587 Send test mail every 30 minutes

---

adminservice/src/main/java/nu/yona/server/AdminServiceApplication.java
analysisservice/src/main/java/nu/yona/server/AnalysisServiceApplication.java
appservice/src/main/java/nu/yona/server/AppServiceApplication.java
batchservice/src/main/java/nu/yona/server/BatchServiceApplication.java
core/build.gradle

The cache metrics are not exposed yet. Once we've upgraded to Spring 5 (see YD-589), we can extend the current solution with cache metrics (YD-590).

YD-586 Enable Micrometer with Prometheus endpoint

---

analysisservice/src/main/java/nu/yona/server/analysis/service/AnalysisEngineService.java

Currently, it just performs a get on the Optional, causing an error with no user anonymized ID. The current patch addresses that.
My suspicion of the issue is that a user deleted their account, causing the user anonymized to be deleted from the database but not from the cache. With improved error handling, we should be able to see that.

YD-593 Throw specific exception when user anon not found

---

appservice/src/intTest/groovy/nu/yona/server/UserTest.groovy
appservice/src/main/java/nu/yona/server/device/rest/DeviceController.java
appservice/src/main/java/nu/yona/server/goals/rest/GoalController.java
appservice/src/main/java/nu/yona/server/subscriptions/rest/UserController.java
batchservice/src/main/java/nu/yona/server/batch/jobs/SendSystemMessageBatchJob.java
batchservice/src/main/java/nu/yona/server/batch/quartz/jobs/PinResetConfirmationCodeSenderQuartzJob.java
core/src/main/java/nu/yona/server/exceptions/InvalidDataException.java
core/src/main/java/nu/yona/server/rest/RestUtil.java
core/src/main/java/nu/yona/server/subscriptions/entities/BuddyConnectMessage.java
core/src/main/resources/messages/messages.properties
core/src/main/resources/messages/messages_nl.properties

Introduced RestUtil.parseUuid and used that where we parse UUIDs. That throws an InvalidDataException, resulting in a 400 status code.

YD-594 Invalid UUID in URL results in 400

---

k8s/helm/yona/requirements.yaml

Goes with the update to helm-charts repo, new rbac for easier deploy / moving away from clusteradmin on things that don't need it, makes "helm install yona" work out of the box

Bump hazelcast version to use new chart

---

k8s/helm/yona/templates/01_configmap_properties.yaml

Helm chart doesn't allow for leaving out max_users, change makes it only set max_users if provided instead of defaulting to 100, makes the app fall back to its default of 1mil.

Allow not setting max_users

---

k8s/helm/yona/values.yaml

All the other environments have their own max_users defined which is lower than required for helm to start parsing it as scientific notation, quotes makes it take it literally.

Quotes to fix helm parsing

---

core/src/main/java/nu/yona/server/analysis/entities/DayActivity.java
core/src/test/java/nu/yona/server/analysis/entities/DayActivityTest.java

On the date a zone enters or leaves daylight saving time, the day has 23 or 25 hours. This can give issues in the spread calculation. When leaving DST (i.e. on a 25-hour day), the calculated number of minutes for a time stamp after the transition needs to be corrected by subtracting 60 minutes. Right after transitioning into DST, we subtract -60 minutes.

YD-600 Spread index calculation considers DST change

---

appservice/src/intTest/groovy/nu/yona/server/BasicBuddyTest.groovy
appservice/src/main/resources/static/swagger/swagger-spec.yaml
core/src/testUtils/groovy/nu/yona/server/test/Buddy.groovy

* The test now verifies that the goals link is loadable and identical on the user embedded in the buddy and the one in the buddy
* Removed the paths from the swagger-spec.yaml that were already removed from the server code

YD-616 Extended test to verify buddy goals loading error

---

core/src/main/java/nu/yona/server/subscriptions/service/UserService.java

Instead of "less than 10% of the current maximum number of users"

YD-617 Warn when less than 100 users can still join

---

appservice/src/main/java/nu/yona/server/subscriptions/rest/BuddyController.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyDto.java

* A buddy always has a user
* The BuddyDto constructor now asserts that
* The BuddyResource now relies on that
The Swagger spec already defined it as mandatory.

YD-619 Simplify Buddy DTO

---

appservice/src/intTest/groovy/nu/yona/server/ActivityTest.groovy
core/src/main/java/nu/yona/server/analysis/service/DayActivityDto.java
core/src/main/java/nu/yona/server/analysis/service/WeekActivityDto.java
core/src/main/java/nu/yona/server/exceptions/InvalidDataException.java
core/src/main/java/nu/yona/server/rest/RestUtil.java
core/src/main/resources/messages/messages.properties
core/src/main/resources/messages/messages_nl.properties
core/src/test/java/nu/yona/server/analysis/service/DayActivityDtoTest.java
core/src/test/java/nu/yona/server/analysis/service/WeekActivityDtoTest.java

Added exception handling. Along with this improved the error logging for invalid UUIDs by including the cause exception.

YD-626 Prevent 500 in invalid date in URL

---

core/src/main/resources/application.properties
dbinit/liquibase.gradle
dbinit/src/main/liquibase/updates/changelog-0020-yd-628.yml
dbinit/src/main/liquibase/updates/updates.yml

* Switched the Hibernate dialect from MySQL to MariaDB
* Corrected two column types from longtext to the appropriate varchar length
* Corrected an issue in the Gradle task liquibasePathingJar: the dependencies for the liquibase configuration weren't included in the pathing JAR
* For uniformity, changed the working directory for the Gradle task liquibaseDiffChangelog to the same one as used for liquibaseUpdate

YD-628 Upgraded to Liquibase Hibernate5 3.7

---

appservice/src/intTest/groovy/nu/yona/server/ActivityTest.groovy

Looking closer into the reported issue, I believe the current behavior is the best we can do. If a user defines a no-go goal, we would like to give an estimated size of the violation. The current time measurement approach is the best we have.
I've extended a test to explicitly assert the behavior for no-go goals too.

YD-630 Explicitly assert time measurement no-go goals

---

appservice/src/intTest/groovy/nu/yona/server/DeviceManagementTest.groovy
core/src/main/java/nu/yona/server/analysis/entities/Activity.java
core/src/main/java/nu/yona/server/analysis/entities/ActivityRepository.java
core/src/main/java/nu/yona/server/device/service/DeviceService.java
core/src/test/java/nu/yona/server/entities/ActivityRepositoryMock.java
core/src/test/java/nu/yona/server/subscriptions/service/migration/AddFirstDeviceTest.java

Activities have an optional reference to the device on which they occurred. If the user deletes the device, the device reference on the related activities is cleared, but the activities are retained.
Along with this fixed the issue that the cached user anonymized wasn't updated when a device was added or removed.

YD-637 Disconnect activities before delete device

---

appservice/src/intTest/groovy/nu/yona/server/DeviceTest.groovy
appservice/src/main/java/nu/yona/server/subscriptions/rest/UserController.java
appservice/src/main/resources/static/swagger/swagger-spec.yaml
core/src/testUtils/groovy/nu/yona/server/test/AppService.groovy
core/src/testUtils/groovy/nu/yona/server/test/User.groovy

Along with this, replaced repeated definition of Firebase instance ID in Swagger spec with a centralized definition

YD-639 Allow Firebase ID on user registration

---

core/src/main/java/nu/yona/server/analysis/entities/DayActivity.java
core/src/main/java/nu/yona/server/analysis/entities/IntervalActivity.java
core/src/main/java/nu/yona/server/subscriptions/entities/BuddyConnectRequestMessage.java
core/src/main/java/nu/yona/server/subscriptions/entities/BuddyConnectResponseMessage.java
core/src/main/java/nu/yona/server/subscriptions/entities/BuddyDeviceChangeMessage.java
core/src/main/java/nu/yona/server/subscriptions/entities/BuddyDisconnectMessage.java
core/src/main/java/nu/yona/server/subscriptions/entities/BuddyInfoChangeMessage.java
core/src/main/java/nu/yona/server/subscriptions/entities/BuddyVpnConnectionStatusChangeMessage.java
dbinit/liquibase.gradle
dbinit/src/main/liquibase/updates/changelog-0021-yd-641.yml
dbinit/src/main/liquibase/updates/updates.yml

The new version addresses a number of issues (most notably liquibase/liquibase-hibernate#134), resulting in much cleaner output for diffChangeLog.
The new version proposes to basically drop all default values. I've accepted most of them in changelog-0021-yd-641.yml. Some however are unjustified and cause runtime issues if they would be dropped. These will still have to be removed from a future generated change log. I will update the wiki page accordingly.
The new version now properly handles a unique constraint on a type, so I've put that back in IntervalActivity.java

YD-641 Upgrade to Liquibase Hibernate5 3.8

---

appservice/src/intTest/groovy/nu/yona/server/DeviceTest.groovy
appservice/src/intTest/groovy/nu/yona/server/UserTest.groovy
core/src/main/java/nu/yona/server/device/service/DeviceService.java

This is in preparation to the new API version that will come with YD-622.
The minimum versions for Android is now:
Code: 218
Version: 1.2
For iOS, it does not matter much, as the iOS app is expired in Test Flight, but to be safe there, we demand the latest version on the iOS master branch:
Code: 166
Version: 1.2

YD-643 Up min app version

---

adminservice/build.gradle
analysisservice/build.gradle
analysisservice/src/test/java/nu/yona/server/analysis/service/ActivityUpdateServiceTest.java
analysisservice/src/test/java/nu/yona/server/analysis/service/AnalysisEngineServiceTest.java
analysisservice/src/test/java/nu/yona/server/analysis/service/AppActivitiesDtoTest.java
appservice/build.gradle
core/build.gradle
core/src/test/java/nu/yona/server/ThymeleafConfigurationTest.java
core/src/test/java/nu/yona/server/analysis/entities/DayActivityTest.java
core/src/test/java/nu/yona/server/analysis/entities/IntervalActivityTestBase.java
core/src/test/java/nu/yona/server/analysis/entities/WeekActivityTest.java
core/src/test/java/nu/yona/server/analysis/service/ActivityServiceTest.java
core/src/test/java/nu/yona/server/analysis/service/DayActivityDtoTest.java
core/src/test/java/nu/yona/server/analysis/service/WeekActivityDtoTest.java
core/src/test/java/nu/yona/server/crypto/pubkey/PublicKeyDecryptorTest.java
core/src/test/java/nu/yona/server/crypto/pubkey/PublicKeyEncryptorTest.java
core/src/test/java/nu/yona/server/crypto/seckey/SecretKeyUtilTest.java
core/src/test/java/nu/yona/server/exceptions/ResourceBasedExceptionTest.java
core/src/test/java/nu/yona/server/subscriptions/entities/UserTest.java
core/src/test/java/nu/yona/server/subscriptions/service/PrivateUserDataMigrationServiceIntegrationTest.java
core/src/test/java/nu/yona/server/subscriptions/service/PrivateUserDataMigrationServiceIntegration_stepOrderTest.java
core/src/test/java/nu/yona/server/test/util/JUnitUtil.java
core/src/test/java/nu/yona/server/util/LockPoolTest.java
core/src/test/java/nu/yona/server/util/TimeUtilTest.java

The class JUnitUtil used org.junit.Assume.assumeThat of JUnit 4. If that assumption failed, JUnit failed the test rather than skipping it. Now the assume is done with org.junit.jupiter.api.Assumptions.assumeTrue.
To prevent such issues, JUnit 4 was removed from the compile-time dependencies of the tests. This required:
* Replacing quite some assertThat calls
* Moving Groovy and Spock from the unit test dependencies and adding them to the integration test dependencies
* Excluding JUnit from the transitive dependencies of the Spring Boot test starter

YD-645 Remove last JUnit 4 dependencies

---

appservice/src/intTest/groovy/nu/yona/server/CreateUserOnBuddyRequestTest.groovy
appservice/src/main/resources/static/swagger/swagger-spec.yaml
core/src/main/java/nu/yona/server/subscriptions/service/BuddyService.java
core/src/main/resources/templates/email/buddy-invitation-subject.txt
core/src/main/resources/templates/email/messages.properties
core/src/main/resources/templates/email/messages_nl.properties
core/src/test/java/nu/yona/server/ThymeleafConfigurationTest.java

Along with this updated the example version code and version number in swagger-spec.yaml, so the default sample can be used immediately, even after we upped the minimum version from 31 to 218.

YD-647 Add user name to email subject

---

appservice/src/intTest/groovy/nu/yona/server/UserTest.groovy
appservice/src/main/java/nu/yona/server/subscriptions/rest/UserController.java
core/src/main/java/nu/yona/server/exceptions/InvalidDataException.java
core/src/main/resources/messages/messages.properties
core/src/main/resources/messages/messages_nl.properties
core/src/testUtils/groovy/nu/yona/server/YonaServer.groovy

If the tempPassword request parameter is not provided, the requestingDeviceId parameter is mandatory. This is now properly checked.

YD-649 Fixed NPE when missing device ID param

---

appservice/src/intTest/groovy/nu/yona/server/CreateUserOnBuddyRequestTest.groovy
appservice/src/intTest/groovy/nu/yona/server/UserTest.groovy
appservice/src/main/java/nu/yona/server/subscriptions/rest/UserController.java

When updating a user created on buddy request, it is possible to provide device information. If the device name is present, the all properties except for the Firebase instance ID are mandatory. This is now enforced.

YD-654 Demand complete device info

---

appservice/src/intTest/groovy/nu/yona/server/OverwriteUserTest.groovy
core/src/main/java/nu/yona/server/messaging/service/MessageService.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyService.java
core/src/main/resources/application.properties

It used to fail in this scenario:
* Richard sends a buddy connect request to Bob
* Bob accepts the request
* Bob overwrites his account before Richard gets the chance to process the buddy connect response message
* Richard now gets a failure on everything because the pending buddy connect response message cannot be processed
The fix is to delete any pending buddy connect response messages of buddies that were deleted while the user was offline.

YD-656 Fixed buddy not found by ID issue

---

appservice/src/intTest/groovy/nu/yona/server/OverwriteUserTest.groovy
core/src/main/java/nu/yona/server/messaging/entities/MessageDestination.java
core/src/main/java/nu/yona/server/messaging/entities/MessageRepository.java
core/src/main/java/nu/yona/server/messaging/entities/MessageSource.java
core/src/main/java/nu/yona/server/messaging/service/MessageDto.java
core/src/main/java/nu/yona/server/messaging/service/MessageService.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyService.java

The related defect is about deleting the unprocessed buddy connect response (acceptance) of a buddy that overwrote their account. That same buddy might also have sent goal conflict messages already. These also need to be removed explicitly.
* Improved error logging in ``MessageDto``
* The ``MessageRepository`` used destination ID often where it could use destination. Refactored this to make the code type-safe and simpler.

YD-657 Delete messages from buddy in incomplete state

---

appservice/src/intTest/groovy/nu/yona/server/AnalysisEngineHibernateStatsTest.groovy
appservice/src/intTest/groovy/nu/yona/server/BasicBuddyTest.groovy
appservice/src/intTest/groovy/nu/yona/server/OverwriteUserTest.groovy
core/src/main/java/nu/yona/server/analysis/service/GoalConflictMessageDto.java
core/src/main/java/nu/yona/server/messaging/entities/BuddyMessage.java
core/src/main/java/nu/yona/server/messaging/entities/Message.java
core/src/main/java/nu/yona/server/messaging/entities/MessageDestination.java
core/src/main/java/nu/yona/server/messaging/service/DisclosureRequestMessageDto.java
core/src/main/java/nu/yona/server/messaging/service/FirebaseService.java
core/src/main/java/nu/yona/server/messaging/service/MessageService.java
core/src/main/java/nu/yona/server/subscriptions/entities/BuddyConnectMessage.java
core/src/main/java/nu/yona/server/subscriptions/entities/BuddyConnectRequestMessage.java
core/src/main/java/nu/yona/server/subscriptions/entities/BuddyConnectionChangeMessage.java
core/src/main/java/nu/yona/server/subscriptions/entities/BuddyDisconnectMessage.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyService.java
core/src/test/java/nu/yona/server/messaging/service/MessageServiceTest.java

This scenario failed:
* User gets invited as buddy
* Invited user overwrites their account
* From the new account, they request the inviting user to become their buddy
* The inviting buddy now cannot process the messages anymore
This was because the direct messages were removed from the named destination and directly inserted in the anonymous destination.
This is now resolved by duplicating the messages. The original one is deleted from the direct destination and a duplicate of it is attached to the anonymous destination.
* Added extra assert to BasicBuddyTest.'Richard finds Bob\'s buddy connect response', to track down a duplicate message issue.
* Updated AnalysisEngineHibernateStatsTest.groovy to lower the number of entities loaded. That somehow improved.
* Removed …

YD-660 Fixed detached entity error

---

appservice/src/intTest/groovy/nu/yona/server/DeviceTest.groovy
core/src/main/java/nu/yona/server/exceptions/InvalidDataException.java
core/src/main/java/nu/yona/server/rest/Constants.java
core/src/main/java/nu/yona/server/rest/ErrorLoggingFilter.java
core/src/main/resources/messages/messages.properties
core/src/main/resources/messages/messages_nl.properties

Added the information from the Yona-App-Version header to the MDC.
Along with this corrected the message IDs of the Dutch messages for PIN reset confirmation codes from "error.pin.reset.overwrite.confirmation" into "error.pin.reset.request.confirmation".

YD-652 Add app version info to logging context

---

appservice/src/main/resources/static/swagger/swagger-spec.yaml
core/src/main/java/nu/yona/server/device/service/DeviceService.java
core/src/main/java/nu/yona/server/subscriptions/entities/User.java
core/src/main/java/nu/yona/server/subscriptions/entities/UserPrivate.java
core/src/main/java/nu/yona/server/subscriptions/entities/UserRepository.java
core/src/main/java/nu/yona/server/subscriptions/service/UserDto.java
core/src/main/java/nu/yona/server/subscriptions/service/migration/EncryptUserCreationTime.java
core/src/test/java/nu/yona/server/device/service/DeviceServiceTest.java
core/src/test/java/nu/yona/server/subscriptions/service/PrivateUserDataMigrationServiceIntegration_stepOrderTest.java
core/src/test/java/nu/yona/server/subscriptions/service/migration/EncryptUserCreationTimeTest.java
core/src/test/java/nu/yona/server/test/util/JUnitUtil.java
dbinit/src/main/liquibase/updates/changelog-0023-yd-662.yml
dbinit/src/main/liquibase/updates/updates.yml

This field is an identification risk. We only use it for management tasks, but for that we don't need the precise date, so we could as well round all creation dates to the first of the month and keep the real creation date encrypted inside UserPrivate.
By keeping it there, we can still see when the user was created and use that for decisions like determining the "earliest possible date" for activities.
The rounding only happens for users that use the app for more than 30 days. This way, we can still get insight in the usage statistics and see early leavers. The risk for these short-term users is lot smaller as they gather little data.

YD-662 Move creation time from User to UserPrivate

---

Jenkinsfile
appservice/src/intTest/groovy/nu/yona/server/AbstractAppServiceIntegrationTest.groovy
appservice/src/intTest/groovy/nu/yona/server/BasicBuddyTest.groovy
appservice/src/intTest/groovy/nu/yona/server/CreateUserOnBuddyRequestTest.groovy
appservice/src/intTest/groovy/nu/yona/server/DeviceTest.groovy
appservice/src/intTest/groovy/nu/yona/server/FirebaseTest.groovy
appservice/src/intTest/groovy/nu/yona/server/LocalizationTest.groovy
appservice/src/intTest/groovy/nu/yona/server/OverwriteUserTest.groovy
appservice/src/intTest/groovy/nu/yona/server/PinResetRequestTest.groovy
appservice/src/intTest/groovy/nu/yona/server/UserTest.groovy
core/src/main/java/nu/yona/server/CoreConfiguration.java
core/src/main/java/nu/yona/server/ThreadScope.java
core/src/main/java/nu/yona/server/messaging/service/FirebaseService.java
core/src/main/java/nu/yona/server/rest/Config.java
core/src/main/java/nu/yona/server/rest/Constants.java
core/src/main/java/nu/yona/server/rest/ErrorLoggingFilter.java
core/src/main/java/nu/yona/server/rest/HeadersClientInterceptor.java
core/src/main/java/nu/yona/server/rest/HeadersHolder.java
core/src/main/java/nu/yona/server/rest/HeadersServerInterceptor.java
core/src/main/java/nu/yona/server/rest/PassThroughHeadersHolder.java
core/src/main/java/nu/yona/server/rest/RestClientErrorHandler.java
core/src/main/java/nu/yona/server/rest/TestController.java
core/src/main/java/nu/yona/server/util/AsyncExecutor.java
core/src/testUtils/groovy/nu/yona/server/YonaServer.groovy
core/src/testUtils/groovy/nu/yona/server/test/AppService.groovy
core/src/testUtils/groovy/nu/yona/server/test/Device.groovy
core/src/testUtils/groovy/nu/yona/server/test/Service.groovy

It now goes from the app service to invoked services (e.g. the analysis service) and also to the async thread that sends the Firebase message, so it can be included in the error logging there.
* Improved the error logging for errors returned from an invoked service
* Included the token in the exception logging for Firebase issues
* Made the parameter order in tests consistent. Now the parameter order is always "parameters, headers", where "headers" can be omitted.

YD-669 Pass app info all the way

---

appservice/src/main/java/nu/yona/server/analysis/rest/BuddyActivityController.java
appservice/src/main/java/nu/yona/server/analysis/rest/UserActivityController.java
appservice/src/main/java/nu/yona/server/device/rest/DeviceController.java
appservice/src/main/java/nu/yona/server/goals/rest/GoalController.java
appservice/src/main/java/nu/yona/server/messaging/rest/MessageController.java
appservice/src/main/java/nu/yona/server/subscriptions/rest/BuddyController.java
appservice/src/main/java/nu/yona/server/subscriptions/rest/NewDeviceRequestController.java
appservice/src/main/java/nu/yona/server/subscriptions/rest/PinResetRequestController.java
appservice/src/main/java/nu/yona/server/subscriptions/rest/UserController.java
appservice/src/main/java/nu/yona/server/subscriptions/rest/UserPhotoController.java
batchservice/src/main/java/nu/yona/server/batch/jobs/ActivityAggregationBatchJob.java
batchservice/src/main/java/nu/yona/server/batch/jobs/ErrorLoggingListener.java
batchservice/src/main/java/nu/yona/server/batch/jobs/SendSystemMessageBatchJob.java
batchservice/src/main/java/nu/yona/server/batch/quartz/TriggerManagementService.java
core/src/main/java/nu/yona/server/Constants.java
core/src/main/java/nu/yona/server/crypto/seckey/WrongPasswordException.java
core/src/main/java/nu/yona/server/exceptions/InvalidDataException.java
core/src/main/java/nu/yona/server/messaging/service/FirebaseService.java
core/src/main/java/nu/yona/server/rest/ErrorLoggingFilter.java
core/src/main/java/nu/yona/server/rest/RestConstants.java
core/src/main/java/nu/yona/server/subscriptions/service/UserServiceException.java
k8s/helm/yona/values.yaml

This is done for internal server errors occurring in HTTP requests and for asynchronous processes (Quartz jobs, batch jobs and async tasks (CompletableFuture.runAsync).
* Renamed nu.yona.server.rest.Constants into RestConstants, to prevent clashes in places where both are needed
* The PASSWORD_HEADER constant was mostly statically imported. Did this now everywhere.

YD-673 Mark fatal issues with ALERT

---

core/src/main/java/nu/yona/server/CoreConfiguration.java
core/src/main/java/nu/yona/server/device/entities/DeviceAnonymized.java
core/src/main/java/nu/yona/server/device/service/DeviceService.java
core/src/main/java/nu/yona/server/device/service/DeviceServiceException.java
core/src/main/java/nu/yona/server/messaging/service/FirebaseService.java
core/src/main/java/nu/yona/server/messaging/service/MessageService.java
core/src/main/java/nu/yona/server/rest/PassThroughHeadersHolder.java
core/src/main/java/nu/yona/server/util/AsyncExecutor.java
core/src/test/java/nu/yona/server/messaging/service/MessageServiceTest.java
core/src/test/java/nu/yona/server/util/AsyncExecutorTest.java
core/src/testUtils/groovy/nu/yona/server/test/Service.groovy

If the Firebase instance ID is not registered anymore, the Firbase web service returns a 404. In that case, we clear the Firebase instance ID on the DeviceAnonymized entity, so we stop trying to push notifications to that device.
* Added a method to find a DeviceAnonymized without having the UserAnonymized ID available. That ID would otherwise be used for logging, but that isn't worth carrying the UserAnonymized around.
* Used the Spring-way of asynchronous execution. This way, the thread is automatically initialized for Spring behavior.
* Fixed an issue in the Groovy Firebase tests that caused intermittent failures because the asynchronous execution wasn't completed before the Firebase message was fetched by the test
* Created a unit test for AsyncExecutor
* Made the …

YD-676 Clear Firebase ID if not registered anymore

---

appservice/src/intTest/groovy/nu/yona/server/ActivityTest.groovy
appservice/src/main/java/nu/yona/server/analysis/rest/UserActivityController.java

Instead of having to process the result in Excel, the data can now be interpreted immediately.

YD-680 Include duration in raw activity report

---

core/src/main/java/nu/yona/server/rest/GlobalExceptionMapping.java

Added MultipartException to the list of exceptions that cause a 400 status to be returned.

YD-679 Return 400 on MultipartException

---

core/src/main/java/nu/yona/server/CoreConfiguration.java
core/src/main/java/nu/yona/server/device/service/DeviceService.java
core/src/main/java/nu/yona/server/messaging/service/FirebaseService.java
core/src/main/java/nu/yona/server/rest/TestController.java
core/src/test/java/nu/yona/server/messaging/service/FirebaseServiceTest.java
core/src/test/java/nu/yona/server/test/util/JUnitUtil.java

* Handle unregistered devices as part of the exception handling rather than in the completion handler. This gives cleaner failure scenarios.
* Remove excess log statement that reported successful send
* Created a unit test that verifies the FirebaseMessaging failure behavior
* Updated TestController to use the much simpler entity model approach introduced with Spring HATEOAS 1.0

YD-678 Improve Firebase implementation

---

core/src/main/resources/application.properties

The old setting (server.use-forward-headers=true) was deprecated. We now use server.forward-headers-strategy=native. The old setting was deprecated to allow different strategies.

YD-681 Use new Spring forward header setting

---

k8s/helm/yona/Chart.yaml
k8s/helm/yona/requirements.yaml
k8s/helm/yona/templates/03_job-liquibase.yaml
k8s/helm/yona/templates/10_deployment_admin.yaml
k8s/helm/yona/templates/10_deployment_analysis.yaml
k8s/helm/yona/templates/10_deployment_app.yaml
k8s/helm/yona/templates/10_deployment_batch.yaml
k8s/helm/yona/values.yaml

Use new updated mariadb and openldap charts for local testing (when support_infrastructure: true) and update app deployments to new api version.

Upgrade helm charts for new API versions

---

core/src/main/resources/application.properties

For both SMTP and SMTPS, all set to three minutes. From infinite to 3 minutes is a significant change. If need be, we reduce the values in a next round.

YD-690 Added SMTP connection timeouts

---

Jenkinsfile

Pure Jenkinsfile update, seems like an upgrade to the Gitlab API throws an error 400 when a file path is absolute/begins with a forward slash

Remove preceding slash for gitlab API call on beta/loadtest

---

core/src/main/java/nu/yona/server/analysis/service/ActivityService.java

We used UTC to determine the user creation date, which caused the test to fail.

YD-691 Use user time zone to determine creation date

---

appservice/src/intTest/groovy/nu/yona/server/BasicBuddyTest.groovy
appservice/src/intTest/groovy/nu/yona/server/OverwriteUserTest.groovy
core/src/main/java/nu/yona/server/subscriptions/entities/BuddyAnonymizedRepository.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyService.java
core/src/test/java/nu/yona/server/entities/BuddyAnonymizedRepositoryMock.java

A device might continue to use its VPN after the user overwrote their account. In that case, new goal conflict messages might be created for a user user anonymized that is orphaned and where the buddies already wiped the related messages and buddy entity. Such a new goal conflict message would lead to an inconsistency where the belonging buddy entity cannot be found.
To fix this, BuddyService.getBuddyUsersAnonymized now does not return buddy entities for which the corresponding buddy entity at the other side does not exist.
This has a minor side effect: earlier, if two users became buddies, the goal conflicts of the accepting user would be reported to the requesting user immediately after the accepting user accepted the request. Now this is delayed a little: goal conflicts of the …

YD-685 Gracefully handle activity on orphaned user anonymized

---

appservice/src/intTest/groovy/nu/yona/server/ActivityTest.groovy
core/src/testUtils/groovy/nu/yona/server/YonaServer.groovy

The week number was wrongly calculated for the week of 30-Dec-2020 (2021-W01 instead of 2020-W53).
Along with this: added a delete for Bea that was forgotten earlier.

YD-699 Correct ISO week number calculation

---

appservice/src/intTest/groovy/nu/yona/server/UserTest.groovy
appservice/src/main/java/nu/yona/server/subscriptions/rest/UserController.java
appservice/src/main/resources/static/swagger/swagger-spec.yaml

The code requires the ID of the requesting device, but the parameter definition and the Swagger spec didn't make that explicit. This is corrected now.
* Updated the Swagger spec for more occurrences where the requesting device ID is mandatory
* Extended the test 'Update John Doe with a different mobile number' to also assert user account enters the regular "mobile number not verified" state, which can be transitioned to "confirmed" through the regular confirmation process.

YD-697 Be explicit about mandatory device ID

---

core/src/main/java/nu/yona/server/messaging/service/FirebaseService.java

The code accidentally passed the Optional to the error log method rather than its value.

YD-705 include exception in Firebase fatal alert

---

adminservice/build.gradle
analysisservice/build.gradle
appservice/build.gradle
batchservice/build.gradle
build.gradle
core/build.gradle
dbinit/build.gradle
dbinit/liquibase.gradle
dependencies.gradle

According to dependabot/feedback#345 we'd need to store this info in a file that contains the plain dependency strings in order for Dependabot to parse our dependencies. Otherwise, we aren't going to reap the benefits of Dependabot for our Java libraries.

Move Java dependency declarations to separate file and format for Dependabot

---

adminservice/src/main/docker/Dockerfile
analysisservice/src/main/docker/Dockerfile
appservice/src/main/docker/Dockerfile
batchservice/src/main/docker/Dockerfile
core/src/main/resources/application.properties

Use TLS 1.2 for SMTP, as the older TLS versions are no longer enabled.

YD-709 Upgrade to Java 1.0.12

---

adminservice/build.gradle
analysisservice/build.gradle
appservice/build.gradle
batchservice/build.gradle
build.gradle
dbinit/build.gradle

Yona is an evergreen cloud product, so we are not doing releases.

Remove Gradle release plugin

---

core/src/main/java/nu/yona/server/device/service/DeviceAnonymizedDto.java

The locale is not set on legacy devices, causing this NPE. The DTO now provides a default. This is fixed on DTO-level as the cache currently already contains legacy instances.

YD-710 Fix NPE when sending system message

---

appservice/src/intTest/groovy/nu/yona/server/ActivityTest.groovy
appservice/src/main/java/nu/yona/server/admin/rest/AdminController.java
core/src/main/java/nu/yona/server/subscriptions/entities/User.java
core/src/main/java/nu/yona/server/subscriptions/service/UserAddService.java
core/src/main/java/nu/yona/server/subscriptions/service/UserUpdateService.java

These log statements were introduced with e9c5df12a477d51cb2649d1da1068b3670843d7f to chase YD-695. That's resolved now, so the debug log statements were obsolete and are now removed.

YD-702 Removed obsolete debug logging
