yonadev/yona-server

core/src/main/java/nu/yona/server/crypto/CryptoSession.java
core/src/main/java/nu/yona/server/subscriptions/entities/User.java
core/src/main/java/nu/yona/server/subscriptions/service/UserService.java
core/src/test/java/nu/yona/server/crypto/CryptoSessionTest.java

Subsequent encryption and decryption actions use the same
initialization vector. The CryptoSession now has the possibility to
generate the initialization vector and set it when reading the data
again.

YD-94 The initialization vector is now stored on User only.

---

appservice/src/intTest/groovy/nu/yona/server/UserTest.groovy
appservice/src/main/java/nu/yona/server/subscriptions/rest/UserController.java
core/src/main/java/nu/yona/server/CoreConfiguration.java
core/src/main/java/nu/yona/server/analysis/service/AnalysisEngineService.java
core/src/main/java/nu/yona/server/properties/YonaProperties.java
core/src/main/java/nu/yona/server/sms/PlivoSmsService.java
core/src/main/java/nu/yona/server/subscriptions/service/LDAPUserService.java
core/src/main/java/nu/yona/server/subscriptions/service/UserDTO.java
core/src/main/java/nu/yona/server/subscriptions/service/UserService.java
core/src/main/resources/application.properties
core/src/testutils/groovy/nu/yona/server/YonaServer.groovy
sqltool.rc

* LDAP can now be disabled
* Corrected ``UserDTO`` (didn't assign ``isConfirmed``, which caused a test case failure).
* Finished the rename from "confirm user" to "confirm mobile number"

YD-107 unify the property handling

---

appservice/src/intTest/groovy/nu/yona/server/BasicBuddyTest.groovy
appservice/src/intTest/groovy/nu/yona/server/RemoveUserTest.groovy
core/src/main/java/nu/yona/server/subscriptions/entities/BuddyAnonymized.java
core/src/main/java/nu/yona/server/subscriptions/entities/BuddyMessage.java
core/src/main/java/nu/yona/server/subscriptions/entities/User.java
core/src/main/java/nu/yona/server/subscriptions/entities/UserAnonymized.java
core/src/main/java/nu/yona/server/subscriptions/entities/UserPrivate.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyDisconnectMessageDTO.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyService.java
core/src/main/java/nu/yona/server/subscriptions/service/UserService.java

Also checking for the case that the buddy connect request was not yet
accepted

YD-121 Disconnecting remote Buddy on remove, removing anonymous messages

---

core/src/main/java/nu/yona/server/sms/SmsService.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyService.java
core/src/main/resources/templates/email/buddy-invitation-body.vm
core/src/main/resources/templates/sms/buddy-invitation.vm

Also added invite message to buddy invite email as it was missing

YD-78 Sending invite SMS

---

appservice/src/intTest/groovy/nu/yona/server/BasicBuddyTest.groovy
appservice/src/intTest/groovy/nu/yona/server/CreateUserOnBuddyRequestTest.groovy
appservice/src/intTest/groovy/nu/yona/server/OverwriteUserTest.groovy
core/src/testUtils/groovy/nu/yona/server/test/AppService.groovy

Is this what you meant? That's quite a bit less code than comment. Sorry for not calling you earlier.

YD-141 move test specific assertion

---

core/src/main/java/nu/yona/server/crypto/LongFieldEncrypter.java
core/src/main/java/nu/yona/server/crypto/UUIDFieldEncrypter.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyConnectRequestMessageDTO.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyConnectResponseMessageDTO.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyService.java
core/src/main/java/nu/yona/server/subscriptions/service/UserService.java

With this, the modified hacking test (see [the JIRA issue](http://jira.yona.nu/browse/YD-134)) succeeds even when run 1000 times.

YD-134 Properly handle decryption failures

---

appservice/src/intTest/groovy/nu/yona/server/OverwriteUserTest.groovy
appservice/src/intTest/groovy/nu/yona/server/UserTest.groovy
appservice/src/main/java/nu/yona/server/subscriptions/rest/UserController.java
core/src/main/java/nu/yona/server/subscriptions/service/UserDTO.java
core/src/testUtils/groovy/nu/yona/server/YonaServer.groovy

This happened to be a test case issue rather than a product issue (except for the ``JsonIgnore`` on ``isMobileNumberConfirmed``).

YD-126 number confirmation link

---

core/src/main/java/nu/yona/server/analysis/entities/Activity.java
core/src/main/java/nu/yona/server/analysis/entities/GoalConflictMessage.java
core/src/main/java/nu/yona/server/analysis/service/AnalysisEngineService.java
core/src/main/java/nu/yona/server/analysis/service/GoalConflictMessageDTO.java
core/src/test/java/nu/yona/server/analysis/service/AnalysisEngineServiceTests.java

Fixed bug that start time was not set to activity
Fixed bug that end time was not set to activity initially

YD-87 Extend unit test for analysisengineservice, fix bugs

---

core/src/test/java/nu/yona/server/analysis/service/AnalysisEngineServiceTests.java

This way of matching retains more of the semantics and shows the compared data in the output upon a mismatch.

YD-154 Introduced Hamcrest matchers

---

appservice/src/intTest/groovy/nu/yona/server/CreateUserOnBuddyRequestTest.groovy

Exceptions were already added by @pgussow

YD-137 Extended and fixed some tests

---

core/src/main/java/nu/yona/server/sms/PlivoSmsService.java

Not yet tested because I do not have a Plivo setup, can somebody do that for me?

YD-157 Migrated to HttpClientBuilder

---

appservice/src/main/java/nu/yona/server/subscriptions/rest/BuddyController.java
core/src/main/java/nu/yona/server/messaging/entities/DiscloseRequestMessage.java
core/src/main/java/nu/yona/server/messaging/entities/DiscloseResponseMessage.java
core/src/main/java/nu/yona/server/subscriptions/entities/BuddyMessage.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyConnectRequestMessageDTO.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyConnectResponseMessageDTO.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyDTO.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyDisconnectMessageDTO.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyMessageDTO.java
core/src/main/java/nu/yona/server/subscriptions/service/UserDTO.java

YD-136 Set UserDTO to null when user removed

---

scripts/smoothwall/HandleDansGuardianLog.pl

The change is simple enough to be understandable for people without Perl knowledge.

YD-167 updated the URL

---

appservice/src/intTest/groovy/nu/yona/server/AbstractAppServiceIntegrationTest.groovy
appservice/src/intTest/groovy/nu/yona/server/CreateUserOnBuddyRequestTest.groovy
appservice/src/intTest/groovy/nu/yona/server/EditGoalsTest.groovy
appservice/src/intTest/groovy/nu/yona/server/OverwriteUserTest.groovy
appservice/src/intTest/groovy/nu/yona/server/RemoveUserTest.groovy
appservice/src/intTest/groovy/nu/yona/server/UserTest.groovy
appservice/src/intTest/groovy/nu/yona/server/UserValidationTest.groovy
appservice/src/main/java/nu/yona/server/goals/rest/GoalController.java
appservice/src/main/java/nu/yona/server/subscriptions/rest/BuddyController.java
appservice/src/main/java/nu/yona/server/subscriptions/rest/UserController.java
core/src/main/java/nu/yona/server/goals/service/BudgetGoalDTO.java
core/src/main/java/nu/yona/server/goals/service/GoalDTO.java
core/src/main/java/nu/yona/server/goals/service/GoalService.java
core/src/main/java/nu/yona/server/goals/service/GoalServiceException.java
core/src/main/java/nu/yona/server/subscriptions/entities/User.java
core/src/main/java/nu/yona/server/subscriptions/entities/UserAnonymized.java
core/src/main/java/nu/yona/server/subscriptions/service/UserDTO.java
core/src/main/java/nu/yona/server/subscriptions/service/UserPrivateDTO.java
core/src/main/java/nu/yona/server/subscriptions/service/UserService.java
core/src/main/resources/messages/messages.properties
core/src/test/java/nu/yona/server/goals/service/ActivityCategoryServiceTests.java
core/src/testUtils/groovy/nu/yona/server/test/AppService.groovy
core/src/testUtils/groovy/nu/yona/server/test/BudgetGoal.groovy
core/src/testUtils/groovy/nu/yona/server/test/Goal.groovy
core/src/testUtils/groovy/nu/yona/server/test/User.groovy
dbinit/data/activityCategories.json

Updating of goals not supported yet

YD-165 implement goals controller, YD-46 embed goals in user

---

appservice/src/intTest/groovy/nu/yona/server/BasicBuddyTest.groovy
appservice/src/intTest/groovy/nu/yona/server/CreateUserOnBuddyRequestTest.groovy
appservice/src/intTest/groovy/nu/yona/server/MessagingTest.groovy
appservice/src/intTest/groovy/nu/yona/server/RemoveUserTest.groovy
appservice/src/main/java/nu/yona/server/messaging/rest/MessageController.java
core/src/main/java/nu/yona/server/messaging/service/MessageService.java
core/src/testUtils/groovy/nu/yona/server/test/AppService.groovy

Following implementation suggestion of @Bert-R

YD-62 Transfering direct messages to anonymous on get

---

appservice/src/intTest/groovy/nu/yona/server/EditGoalsTest.groovy
appservice/src/main/java/nu/yona/server/subscriptions/rest/BuddyController.java
appservice/src/main/java/nu/yona/server/subscriptions/rest/UserController.java
core/src/testUtils/groovy/nu/yona/server/test/AppService.groovy
core/src/testUtils/groovy/nu/yona/server/test/User.groovy

Checked all _embedded resources, and refactored the embedded buddies to a collection resource.
Next step is to use curies to make these links custom, I propose that this is picked up together with YD-172 or otherwise this task can remain open.

YD-174 add collection links

---

appservice/src/intTest/groovy/nu/yona/server/BasicBuddyTest.groovy
appservice/src/intTest/groovy/nu/yona/server/RejectBuddyTest.groovy
appservice/src/intTest/groovy/nu/yona/server/RemoveUserTest.groovy
core/src/main/java/nu/yona/server/subscriptions/service/BuddyConnectResponseMessageDTO.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyDisconnectMessageDTO.java

If the message is processed is now only visible by if the "process" _link is included

YD-179 Added @JsonIgnore to isProcessed()

---

adminservice/src/main/java/nu/yona/server/goals/rest/ActivityCategoryController.java
analysisservice/src/main/java/nu/yona/server/analysis/rest/AnalysisEngineController.java
appservice/src/main/java/nu/yona/server/goals/rest/ActivityCategoryController.java
appservice/src/main/java/nu/yona/server/goals/rest/GoalController.java
appservice/src/main/java/nu/yona/server/messaging/rest/MessageController.java
appservice/src/main/java/nu/yona/server/subscriptions/rest/BuddyController.java
appservice/src/main/java/nu/yona/server/subscriptions/rest/UserController.java

And put them in a logical order

YD-75 Moved all request-mapped methods together

---

adminservice/src/main/java/nu/yona/server/AdminServiceApplication.java
analysisservice/src/main/java/nu/yona/server/AnalysisServiceApplication.java
appservice/src/main/java/nu/yona/server/AppServiceApplication.java
build.gradle

Removed the workaround for spring-projects/spring-boot#4919, as that issue is fixed.

YD-153 Upgraded to Spring Boot 1.3.2

---

appservice/src/intTest/groovy/nu/yona/server/AbstractAppServiceIntegrationTest.groovy
appservice/src/intTest/groovy/nu/yona/server/CreateUserOnBuddyRequestTest.groovy
appservice/src/intTest/groovy/nu/yona/server/EditGoalsTest.groovy
appservice/src/intTest/groovy/nu/yona/server/OverwriteUserTest.groovy
appservice/src/intTest/groovy/nu/yona/server/UserTest.groovy
appservice/src/main/java/nu/yona/server/goals/rest/GoalController.java
core/src/main/java/nu/yona/server/goals/entities/ActivityCategory.java
core/src/main/java/nu/yona/server/goals/entities/BudgetGoal.java
core/src/main/java/nu/yona/server/goals/entities/Goal.java
core/src/main/java/nu/yona/server/goals/service/ActivityCategoryDTO.java
core/src/main/java/nu/yona/server/goals/service/BudgetGoalDTO.java
core/src/main/java/nu/yona/server/goals/service/GoalDTO.java
core/src/main/java/nu/yona/server/goals/service/GoalService.java
core/src/main/java/nu/yona/server/goals/service/GoalServiceException.java
core/src/main/java/nu/yona/server/subscriptions/service/UserService.java
core/src/main/resources/messages/messages.properties
dbinit/data/activityCategories.json

Renamed property on ActivityCategory, blocking remove, added/updated
tests

YD-158 Automatically adding mandatory goal

---

appservice/src/intTest/groovy/nu/yona/server/AbstractAppServiceIntegrationTest.groovy
appservice/src/intTest/groovy/nu/yona/server/AppActivityTest.groovy
appservice/src/intTest/groovy/nu/yona/server/BasicBuddyTest.groovy
appservice/src/intTest/groovy/nu/yona/server/DisclosureTest.groovy
appservice/src/intTest/groovy/nu/yona/server/EditGoalsTest.groovy
core/src/main/resources/application.properties
core/src/testUtils/groovy/nu/yona/server/YonaServer.groovy
core/src/testUtils/groovy/nu/yona/server/test/AppActivity.groovy
core/src/testUtils/groovy/nu/yona/server/test/AppService.groovy

YD-191 Use standard date/time instead of epoch

---

core/src/main/java/nu/yona/server/crypto/PublicKeyUtil.java
core/src/main/java/nu/yona/server/subscriptions/service/LDAPUserService.java
core/src/testUtils/groovy/nu/yona/server/test/Buddy.groovy

Marked static class as final
Removed some unnecessary TODOs

YD-182 remove warning

---

appservice/src/main/java/nu/yona/server/AppServiceApplication.java
appservice/src/main/resources/static/swagger/swagger-spec.yaml
core/src/main/java/nu/yona/server/properties/SecurityProperties.java
core/src/main/resources/application.properties

This is required to test the API from Swagger UI.

YD-177 Optionally enabled CORS for everything

---

appservice/src/main/java/nu/yona/server/AppServiceApplication.java

YD-177 Enabled CORS all HTTP methods

---

appservice/src/intTest/groovy/nu/yona/server/LocalizationTest.groovy
appservice/src/main/java/nu/yona/server/appresources/LocalizationFilter.java
appservice/src/main/resources/static/resources/android/en-US/trialresource.properties
appservice/src/main/resources/static/resources/android/nl-NL/trialresource.properties
appservice/src/main/resources/static/resources/iOS/en-US/trialresource.properties
appservice/src/main/resources/static/resources/iOS/nl-NL/trialresource.properties
core/src/main/java/nu/yona/server/Translator.java
core/src/main/java/nu/yona/server/email/EmailService.java
core/src/main/java/nu/yona/server/properties/YonaProperties.java
core/src/main/java/nu/yona/server/sms/PlivoSmsService.java
core/src/main/resources/application.properties
core/src/main/resources/messages/messages_nl.properties
core/src/main/resources/templates/email/buddy-invitation-body.vm
core/src/main/resources/templates/email/buddy-invitation-body_nl.vm
core/src/main/resources/templates/email/buddy-invitation-subject_nl.vm
core/src/main/resources/templates/sms/add-user-number-confirmation_nl.vm
core/src/main/resources/templates/sms/buddy-invitation_nl.vm
core/src/main/resources/templates/sms/changed-user-number-confirmation_nl.vm
core/src/main/resources/templates/sms/overwrite-user-number-confirmation_nl.vm

* All localizable resources are now available in Dutch
* Implemented language fallback
* Implemented capability to fetch localized resources for the apps
* Now returns the Content-Language header, to show the result of language negotiation

YD-211 Completed localization support

---

appservice/src/intTest/groovy/nu/yona/server/AddDeviceTest.groovy
appservice/src/main/java/nu/yona/server/subscriptions/rest/NewDeviceRequestController.java
core/src/main/java/nu/yona/server/subscriptions/entities/NewDeviceRequest.java
core/src/main/java/nu/yona/server/subscriptions/service/DeviceRequestException.java
core/src/main/java/nu/yona/server/subscriptions/service/NewDeviceRequestService.java
core/src/main/java/nu/yona/server/subscriptions/service/UserService.java
core/src/main/resources/messages/messages.properties

It shouldn't be possible to see whether a mobile number exists, except during the short moment the new device request exists.

YD-213 Prevent information leakage through error codes

---

appservice/src/intTest/groovy/nu/yona/server/UserValidationTest.groovy
core/src/main/java/nu/yona/server/exceptions/InvalidDataException.java
core/src/main/java/nu/yona/server/subscriptions/service/UserService.java
core/src/main/resources/messages/messages.properties
core/src/main/resources/messages/messages_nl.properties

Added a check on nickname not being null in validation of the user fields in the user service.

YD-193 nickname not null

---

appservice/src/main/java/nu/yona/server/analysis/rest/AppActivityController.java
core/src/main/java/nu/yona/server/analysis/service/AnalysisEngineService.java
core/src/test/java/nu/yona/server/analysis/service/AnalysisEngineServiceTests.java

Assumption: activity never crosses 2 days

YD-207 Fixed cross-day app activity

---

core/src/main/java/nu/yona/server/analysis/service/ActivityService.java

Methods and variables updated too.

YD-208 Further renames of startEndDate

---

appservice/src/main/java/nu/yona/server/goals/rest/GoalController.java
appservice/src/main/resources/static/swagger/swagger-spec.yaml
core/src/main/java/nu/yona/server/exceptions/InvalidDataException.java
core/src/main/java/nu/yona/server/goals/service/BudgetGoalDTO.java
core/src/main/java/nu/yona/server/goals/service/GoalDTO.java
core/src/main/java/nu/yona/server/goals/service/TimeZoneGoalDTO.java
core/src/main/resources/messages/messages.properties
core/src/main/resources/messages/messages_nl.properties
core/src/testUtils/groovy/nu/yona/server/test/BudgetGoal.groovy
core/src/testUtils/groovy/nu/yona/server/test/TimeZoneGoal.groovy

This by nature creates the code structure as requested in the previous review.

YD-222 The activity category URL is now in _links

---

appservice/src/intTest/groovy/nu/yona/server/BasicBuddyTest.groovy
appservice/src/intTest/groovy/nu/yona/server/CreateUserOnBuddyRequestTest.groovy
appservice/src/main/java/nu/yona/server/subscriptions/rest/BuddyController.java
appservice/src/main/resources/static/swagger/swagger-spec.yaml
core/src/main/java/nu/yona/server/subscriptions/service/BuddyDTO.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyServiceException.java
core/src/main/resources/messages/messages.properties
core/src/main/resources/messages/messages_nl.properties
core/src/testUtils/groovy/nu/yona/server/test/AppService.groovy

* Embedded user as yona:user
* Introduced a small DTO for posting a buddy, inside the controller. The controller handles the _embedded entity with it
* Corrected the Swagger spec
* Now omits the nickname from the buddy when it is not available

YD-215 Corrected post of buddyService

---

appservice/src/intTest/groovy/nu/yona/server/AppActivityTest.groovy
appservice/src/main/java/nu/yona/server/analysis/rest/AppActivityController.java
appservice/src/main/resources/static/swagger/swagger-spec.yaml
core/src/main/java/nu/yona/server/analysis/service/AnalysisEngineService.java
core/src/main/java/nu/yona/server/analysis/service/AppActivityDTO.java
core/src/test/java/nu/yona/server/analysis/service/AnalysisEngineServiceTests.java
core/src/testUtils/groovy/nu/yona/server/test/AppActivity.groovy
core/src/testUtils/groovy/nu/yona/server/test/AppService.groovy

Based on this, the time stamps of the reported app activity events are corrected. Along with this change, the API is added the the Swagger spec. This was somehow forgotten.

YD-195 Include device time in app activity report

---

core/src/main/java/nu/yona/server/subscriptions/service/UserService.java

Instead of the object containing it

YD-231 Now sends the confirmation code

---

core/src/main/resources/templates/email/buddy-invitation-body.vm
core/src/main/resources/templates/email/buddy-invitation-body_nl.vm

YD-232 Correct mail templates

---

appservice/src/intTest/groovy/nu/yona/server/EditGoalsTest.groovy
core/src/main/java/nu/yona/server/goals/entities/TimeZoneGoal.java
core/src/main/java/nu/yona/server/goals/service/TimeZoneGoalDTO.java
core/src/test/java/nu/yona/server/analysis/service/ActivityServiceTests.java
core/src/test/java/nu/yona/server/analysis/service/AnalysisEngineServiceTests.java

And enabled 24:00 as end time.

YD-266 Fixed time zone length bug

---

appservice/src/intTest/groovy/nu/yona/server/AbstractAppServiceIntegrationTest.groovy
appservice/src/intTest/groovy/nu/yona/server/ActivityTest.groovy
appservice/src/main/java/nu/yona/server/analysis/rest/ActivityControllerBase.java
appservice/src/main/java/nu/yona/server/analysis/rest/BuddyActivityController.java
appservice/src/main/java/nu/yona/server/analysis/rest/UserActivityController.java
core/src/main/java/nu/yona/server/analysis/service/ActivityService.java
core/src/main/java/nu/yona/server/properties/AnalysisServiceProperties.java
core/src/main/java/nu/yona/server/subscriptions/service/UserAnonymizedDTO.java
core/src/main/resources/application.properties

Using oldest goal creation time to determine total number of days/weeks available
Default page size 3 for days, 2 for weeks
Removed duplicate old style tests
Added some asserts for pagination in tests

YD-252 Activity pagination

---

appservice/src/intTest/groovy/nu/yona/server/AbstractAppServiceIntegrationTest.groovy
appservice/src/intTest/groovy/nu/yona/server/ActivityTest.groovy
appservice/src/intTest/groovy/nu/yona/server/AppActivityTest.groovy
appservice/src/intTest/groovy/nu/yona/server/BasicBuddyTest.groovy
appservice/src/intTest/groovy/nu/yona/server/DisclosureTest.groovy
appservice/src/intTest/groovy/nu/yona/server/EditGoalsTest.groovy
appservice/src/intTest/groovy/nu/yona/server/PinResetRequestTest.groovy
core/src/testUtils/groovy/nu/yona/server/YonaServer.groovy
core/src/testUtils/groovy/nu/yona/server/test/AppActivity.groovy

* Centralized "now" in YonaServer.now
* Added the test

YD-268 Test adding activity after retrieving report

---

analysisservice/src/intTest/groovy/nu/yona/server/RelevantSmoothwallCategoriesTest.groovy
appservice/src/main/java/nu/yona/server/subscriptions/rest/PinResetRequestController.java
dbinit/data/activityCategories.json

YD-270 extend activity categories

---

appservice/src/intTest/groovy/nu/yona/server/ActivityTest.groovy
appservice/src/main/java/nu/yona/server/analysis/rest/BuddyActivityController.java
core/src/testUtils/groovy/nu/yona/server/test/Buddy.groovy

Corrected the URL and added very basic test.

YD-279 Wrong goal URL in day activity overview for buddy

---

appservice/src/main/java/nu/yona/server/analysis/rest/UserActivityController.java
core/src/main/java/nu/yona/server/analysis/service/DayActivityWithBuddiesDTO.java

The same property was added through the DTO and the resource. Added a @JsonIgnore property on the DTO.

YD-281 Removed duplicate dayActivitiesForUsers property

---

appservice/src/intTest/groovy/nu/yona/server/BasicBuddyTest.groovy

To verify that disconnect from both ends (the original requester and the other side) works as expected.

YD-283 Mirrored the buddy disconnect

---

appservice/src/intTest/groovy/nu/yona/server/ActivityTest.groovy
core/src/main/java/nu/yona/server/analysis/entities/DayActivityRepository.java
core/src/main/java/nu/yona/server/analysis/service/ActivityCacheService.java

* Added a test to reproduce the issue
* Fixed the issue using Pageable. Spring Data JPA also supports findTop, but that does not go along with a custom query. Using the Spring Data JPA solution doesn't work because that would require the UserAnonymized and Goal entities while we only have the DTOs.

YD-304 Add app activity fails

---

appservice/src/intTest/groovy/nu/yona/server/ActivityTest.groovy
core/src/main/java/nu/yona/server/messaging/entities/MessageRepository.java

The oldest one is coming first now. Updated the test accordingly.

YD-315 Changed sort order activity comment messages

---

core/src/main/java/nu/yona/server/entities/RepositoryProvider.java
core/src/test/java/nu/yona/server/analysis/service/ActivityServiceTests.java
core/src/test/java/nu/yona/server/goals/service/ActivityCategoryServiceTestBase.java

Fixed NullPointerExceptions caused by the DayActivity.getRepository in WeekActivity and save calls

YD-287 fix activity service tests

---

core/src/main/java/nu/yona/server/analysis/service/ActivityCacheService.java
core/src/main/java/nu/yona/server/analysis/service/AnalysisEngineService.java
core/src/main/java/nu/yona/server/subscriptions/service/UserService.java

Not yet reproduced, but code analysed and some @Transactional annotations added which may help keeping the cached entities in sync (if this is the issue)

YD-295 Activity caching issues

---

appservice/src/intTest/groovy/nu/yona/server/ActivityTest.groovy
core/src/main/java/nu/yona/server/subscriptions/service/UserAnonymizedService.java

Because appservice and analysisservice do not share the cache currently, the analysisservice cache is invalid

YD-295 Disabling UserAnonymizedService caching temporarily

---

appservice/src/intTest/groovy/nu/yona/server/BasicBuddyTest.groovy
appservice/src/main/java/nu/yona/server/analysis/rest/ActivityControllerBase.java
appservice/src/main/java/nu/yona/server/messaging/rest/MessageController.java

Consistent with activity comment link

YD-335 Fix goal conflict day detail link name

---

.gitattributes
core/src/main/resources/templates/apple.mobileconfig.vm

Fixed \r\n to \n
Fixed \n in username\npassword
Other changes by Anders

Fix apple mobileconfig

---

appservice/src/intTest/groovy/nu/yona/server/AbstractAppServiceIntegrationTest.groovy
appservice/src/intTest/groovy/nu/yona/server/BasicBuddyTest.groovy
appservice/src/main/java/nu/yona/server/analysis/rest/ActivityControllerBase.java
appservice/src/main/java/nu/yona/server/messaging/rest/MessageController.java
appservice/src/main/resources/static/swagger/swagger-spec.yaml
core/src/main/java/nu/yona/server/analysis/service/ActivityCommentMessageDTO.java
core/src/main/java/nu/yona/server/analysis/service/ActivityService.java
core/src/main/java/nu/yona/server/analysis/service/GoalConflictMessageDTO.java
core/src/main/java/nu/yona/server/goals/service/GoalChangeMessageDTO.java
core/src/main/java/nu/yona/server/messaging/entities/BuddyMessage.java
core/src/main/java/nu/yona/server/messaging/entities/Message.java
core/src/main/java/nu/yona/server/messaging/entities/MessageDestination.java
core/src/main/java/nu/yona/server/messaging/service/BuddyMessageDTO.java
core/src/main/java/nu/yona/server/messaging/service/BuddyMessageEmbeddedUserDTO.java
core/src/main/java/nu/yona/server/messaging/service/BuddyMessageLinkedUserDTO.java
core/src/main/java/nu/yona/server/messaging/service/DisclosureRequestMessageDTO.java
core/src/main/java/nu/yona/server/messaging/service/DisclosureResponseMessageDTO.java
core/src/main/java/nu/yona/server/messaging/service/MessageDTO.java
core/src/main/java/nu/yona/server/messaging/service/SenderInfo.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyConnectRequestMessageDTO.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyConnectResponseMessageDTO.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyDTO.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyDisconnectMessageDTO.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyService.java
core/src/main/java/nu/yona/server/subscriptions/service/UserDTO.java
core/src/test/java/nu/yona/server/analysis/service/AnalysisEngineServiceTests.java

Along with this, refactored the use of SenderInfo to deduplicate and streamline the code

YD-344 Add buddy link to goal conflict message, if from buddy

---

appservice/src/intTest/groovy/nu/yona/server/ActivityTest.groovy
appservice/src/intTest/groovy/nu/yona/server/RemoveUserTest.groovy
appservice/src/main/java/nu/yona/server/messaging/rest/MessageController.java
core/src/testUtils/groovy/nu/yona/server/test/AppService.groovy

I would like to have a reproduce that can be added to the integration
test suite. I have asked Enosh if he can send us a full Charles log.

YD-353 Fixing exception, no reproduce yet

---

core/src/main/java/nu/yona/server/analysis/entities/DayActivity.java
core/src/main/java/nu/yona/server/analysis/entities/WeekActivity.java
core/src/main/java/nu/yona/server/analysis/service/ActivityCacheService.java
core/src/main/java/nu/yona/server/analysis/service/AnalysisEngineService.java

To trace the creation and lookup of day and week activities

YD-295 Added extra log messages

---

appservice/src/intTest/groovy/nu/yona/server/EditGoalsTest.groovy
appservice/src/main/java/nu/yona/server/messaging/rest/MessageController.java
appservice/src/main/resources/static/swagger/swagger-spec.yaml

And removed the DailyActivityReportsLink, as that is of no use.

YD-363 Added buddy link to GoalChangeMessage

---

appservice/src/intTest/groovy/nu/yona/server/UserTest.groovy
appservice/src/main/java/nu/yona/server/rest/AppleAppSiteAssociationController.java
core/build.gradle
core/src/main/java/nu/yona/server/properties/YonaProperties.java
core/src/main/resources/application.properties
core/src/main/resources/templates/apple-app-site-association.vm

Default set to SFWNSYN8YK.com.xaton.yona (test ID)

YD-364 Added configurable Apple App ID

---

adminservice/src/intTest/groovy/nu/yona/server/ActivityCategoriesTest.groovy
analysisservice/src/test/java/nu/yona/server/analysis/service/ActivityServiceTests.java
analysisservice/src/test/java/nu/yona/server/analysis/service/AnalysisEngineServiceTests.java
analysisservice/src/test/java/nu/yona/server/analysis/service/DayActivityTests.java
appservice/src/intTest/groovy/nu/yona/server/ActivityCategoriesTest.groovy
appservice/src/intTest/groovy/nu/yona/server/LocalizationTest.groovy
appservice/src/main/resources/static/swagger/swagger-spec.yaml
core/src/main/java/nu/yona/server/goals/entities/ActivityCategory.java
core/src/main/java/nu/yona/server/goals/service/ActivityCategoryDTO.java
core/src/main/java/nu/yona/server/goals/service/ActivityCategoryService.java
core/src/main/java/nu/yona/server/goals/service/GoalService.java
core/src/test/java/nu/yona/server/goals/service/ActivityCategoryServiceIntegrationTest.java
core/src/test/java/nu/yona/server/goals/service/ActivityCategoryServiceTest.java
core/src/test/java/nu/yona/server/goals/service/ActivityCategoryServiceTestBase.java
dbinit/data/activityCategories.json

Along with this added a new activity category: Gambling.
**Note**: this pull request is based on #253. Once that one is merged, built and delivered, this one can be merged. Not earlier, as that would make it impossible to bring YD-279 separately into the acceptance test.

YD-271 Added localizable description to activity category

---

adminservice/build.gradle
adminservice/src/main/docker/Dockerfile
analysisservice/build.gradle
analysisservice/src/main/docker/Dockerfile
appservice/build.gradle
appservice/src/main/docker/Dockerfile
batchservice/build.gradle
batchservice/src/main/docker/Dockerfile
dbinit/src/main/docker/Dockerfile

* We are not using WARs but JARs, so removed the WAR plug-in. This results in creation of ...-full.jar files
* Updated the Dockerfile for all images to add the ...-full.jar

YD-374 Corrected build script and docker files

---

adminservice/src/main/docker/Dockerfile
analysisservice/src/main/docker/Dockerfile
appservice/src/main/docker/Dockerfile
batchservice/src/main/docker/Dockerfile
dbinit/src/main/docker/Dockerfile

This is already taken care of as part of the Gradle script

YD-374 reverted Dockerfile change

---

docker-compose/yona/docker-compose.yml

From "udp://localhost:12201" to "udp://log:12201"

YD-375 Updated gelf-address

---

analysisservice/src/main/java/nu/yona/server/analysis/service/AnalysisEngineService.java
analysisservice/src/test/java/nu/yona/server/analysis/service/AnalysisEngineServiceTests.java

Exception could occur around 00:00 when trying to combine with the
previous activity.

YD-379 Fixed introduced NullPointerException

---

appservice/src/intTest/groovy/nu/yona/server/EditGoalsTest.groovy
core/src/main/java/nu/yona/server/properties/YonaProperties.java
core/src/main/java/nu/yona/server/subscriptions/service/UserService.java
core/src/main/resources/application.properties

There are now two properties, one whether invited users are checked against the white list and one for free sign up (users that are not invited).

YD-410 Added white list properties

---

core/src/main/java/nu/yona/server/batch/client/BatchProxyService.java
core/src/main/java/nu/yona/server/properties/YonaProperties.java

YD-409 Renamed properties ``yona.batch.*`` into ``yona.batchService.*``

YD-409 Improve batch triggering

---

core/src/main/resources/templates/sms/buddy-invitation.txt
core/src/test/java/nu/yona/server/templates/TemplateTest.java

The template expected a requestingUserName insertion, but this should have been requestingUserFirstName

YD 420 null in sms

---

analysisservice/src/main/java/nu/yona/server/analysis/service/AnalysisEngineService.java
appservice/src/intTest/groovy/nu/yona/server/BasicBuddyTest.groovy
appservice/src/intTest/groovy/nu/yona/server/BuddyValidationTest.groovy
appservice/src/intTest/groovy/nu/yona/server/UserValidationTest.groovy
appservice/src/main/java/nu/yona/server/subscriptions/rest/NewDeviceRequestController.java
core/src/main/java/nu/yona/server/crypto/CryptoUtil.java
core/src/main/java/nu/yona/server/goals/service/ActivityCategoryService.java
core/src/main/java/nu/yona/server/goals/service/GoalService.java
core/src/main/java/nu/yona/server/goals/service/TimeZoneGoalDto.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyService.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyServiceException.java
core/src/main/java/nu/yona/server/subscriptions/service/UserService.java
core/src/main/java/nu/yona/server/subscriptions/service/WhiteListedNumberService.java
core/src/main/resources/messages/messages.properties
core/src/main/resources/messages/messages_nl.properties
core/src/testUtils/groovy/nu/yona/server/test/AppService.groovy

* Verify first and last name is given, as well as a valid mobile number
* Verify that mobile number is not of the inviting user, not an already existing buddy

YD-286 YD-299 Validate buddy data

---

Jenkinsfile

See https://jenkins.io/doc/book/pipeline/syntax/#environment for more info. =) You can also put all the `FOO = credentials('id')` into the `environment` at the top level and avoid the duplication if you prefer. Hope this is helpful!

Declarative Pipelines' credentials support =)

---

analysisservice/src/test/java/nu/yona/server/analysis/service/DayActivityTests.java
analysisservice/src/test/java/nu/yona/server/analysis/service/IntervalActivityTestsBase.java
analysisservice/src/test/java/nu/yona/server/analysis/service/WeekActivityTests.java
appservice/src/intTest/groovy/nu/yona/server/AbstractAppServiceIntegrationTest.groovy
appservice/src/intTest/groovy/nu/yona/server/ActivityAggregationBatchJobTest.groovy
appservice/src/intTest/groovy/nu/yona/server/ActivityTest.groovy
batchservice/src/main/java/nu/yona/server/batch/jobs/ActivityAggregationBatchJob.java
batchservice/src/main/java/nu/yona/server/batch/jobs/PinResetConfirmationCodeSenderBatchJob.java
batchservice/src/main/java/nu/yona/server/batch/rest/BatchTaskController.java
batchservice/src/main/java/nu/yona/server/batch/service/ActivityAggregationBatchJobResultDto.java
batchservice/src/main/java/nu/yona/server/batch/service/BatchTaskService.java
core/src/main/java/nu/yona/server/analysis/entities/Activity.java
core/src/main/java/nu/yona/server/analysis/entities/DayActivity.java
core/src/main/java/nu/yona/server/analysis/entities/IntervalActivity.java
core/src/main/java/nu/yona/server/analysis/entities/WeekActivity.java
core/src/main/java/nu/yona/server/properties/BatchServiceProperties.java
core/src/main/resources/application.properties
core/src/testUtils/groovy/nu/yona/server/test/BatchService.groovy

- Pruning of activities not implemented yet, because the first part is already quite a lot of work

YD-162 Daily aggregation batch job part 1

---

batchservice/src/main/java/nu/yona/server/batch/quartz/SchedulingService.java
core/src/main/java/nu/yona/server/exceptions/BatchException.java
core/src/main/java/nu/yona/server/exceptions/UpstreamException.java
core/src/main/java/nu/yona/server/rest/RestClientErrorHandler.java
core/src/main/resources/messages/messages.properties
core/src/main/resources/messages/messages_nl.properties
scripts/install-test-server.sh

* Added the batch and trigger loading to the test server setup script
* Improved error checking and logging

YD-429 Fixed PIN reset request tests

---

core/src/main/java/nu/yona/server/subscriptions/service/BuddyDto.java

Now returns null when the lastStatusChangeTime == null, and logs the buddy ID, so we can find out what user has this issue.

YD-440 Stop gap solution for lastStatusChangeTime NPE

---

core/src/main/java/nu/yona/server/subscriptions/entities/User.java
core/src/main/java/nu/yona/server/subscriptions/entities/UserPrivate.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyConnectResponseMessageDto.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyDisconnectMessageDto.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyService.java

Along with this added extra logging

YD-442 Remove BuddyAnonymized on disconnect

---

appservice/src/main/java/nu/yona/server/subscriptions/rest/PinResetRequestController.java
appservice/src/main/java/nu/yona/server/subscriptions/rest/UserController.java
core/src/main/java/nu/yona/server/rest/ErrorLoggingFilter.java
core/src/main/java/nu/yona/server/rest/GlobalExceptionMapping.java

* For unhandled exceptions, include the request URL
* Concatenate the query string to the URL, when present

YD-444 Improve error logging

---

appservice/src/intTest/groovy/nu/yona/server/CreateUserOnBuddyRequestTest.groovy
appservice/src/main/java/nu/yona/server/subscriptions/rest/UserController.java
core/src/main/java/nu/yona/server/subscriptions/service/UserService.java
core/src/main/java/nu/yona/server/subscriptions/service/UserServiceException.java
core/src/main/resources/messages/messages.properties
core/src/main/resources/messages/messages_nl.properties
core/src/testUtils/groovy/nu/yona/server/test/AppService.groovy

Along with this added extra test to verify proper usage of the tempPassword query parameter

YD-450 Server generated password for user created on buddy request

---

core/src/main/java/nu/yona/server/analysis/entities/DayActivity.java

Currently the associations caused extra SELECT queries with every fetch
of a DayActivity

YD-453 Fetching WeekActivity/Activity set lazily when fetching DayActivity

---

appservice/src/main/java/nu/yona/server/subscriptions/rest/UserController.java
core/src/main/java/nu/yona/server/properties/AppleMobileConfigProperties.java
core/src/main/resources/application.properties

Though with an option to switch it off through a property

YD-460 Switch signing on

---

core/src/main/java/nu/yona/server/Translator.java
core/src/main/java/nu/yona/server/analysis/service/ActivityServiceException.java
core/src/main/java/nu/yona/server/crypto/CryptoException.java
core/src/main/java/nu/yona/server/crypto/seckey/WrongPasswordException.java
core/src/main/java/nu/yona/server/exceptions/AnalysisException.java
core/src/main/java/nu/yona/server/exceptions/BatchException.java
core/src/main/java/nu/yona/server/exceptions/ConfirmationException.java
core/src/main/java/nu/yona/server/exceptions/EmailException.java
core/src/main/java/nu/yona/server/exceptions/InvalidDataException.java
core/src/main/java/nu/yona/server/exceptions/InvalidMessageActionException.java
core/src/main/java/nu/yona/server/exceptions/MobileNumberConfirmationException.java
core/src/main/java/nu/yona/server/exceptions/PinResetRequestConfirmationException.java
core/src/main/java/nu/yona/server/exceptions/ResourceBasedException.java
core/src/main/java/nu/yona/server/exceptions/SmsException.java
core/src/main/java/nu/yona/server/exceptions/UpstreamException.java
core/src/main/java/nu/yona/server/exceptions/UserOverwriteConfirmationException.java
core/src/main/java/nu/yona/server/exceptions/YonaException.java
core/src/main/java/nu/yona/server/goals/service/ActivityCategoryException.java
core/src/main/java/nu/yona/server/goals/service/GoalServiceException.java
core/src/main/java/nu/yona/server/messaging/service/MessageNotFoundException.java
core/src/main/java/nu/yona/server/messaging/service/MessageServiceException.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyNotFoundException.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyServiceException.java
core/src/main/java/nu/yona/server/subscriptions/service/DeviceRequestException.java
core/src/main/java/nu/yona/server/subscriptions/service/LDAPUserServiceException.java
core/src/main/java/nu/yona/server/subscriptions/service/UserServiceException.java
core/src/main/java/nu/yona/server/subscriptions/service/WhiteListedNumberServiceException.java
core/src/test/java/nu/yona/server/exceptions/ResourceBasedExceptionTest.java

All parameters given to a ResourceBasedException now must implement java.io.Serializable

YD-463 Made ResourceBasedException serializable

---

appservice/src/intTest/groovy/nu/yona/server/UserTest.groovy
appservice/src/main/java/nu/yona/server/subscriptions/rest/UserController.java
appservice/src/main/resources/static/swagger/swagger-spec.yaml
core/src/testUtils/groovy/nu/yona/server/test/User.groovy

This reverts commit 017327c5ae0dea5d0bf91a06692b083e96150fde.

YD-465 Revert "YD-464 Added base-64 encoded Mobile Config (#364)"

---

Jenkinsfile
adminservice/build.gradle
analysisservice/build.gradle
appservice/build.gradle
k8s/helm/yona/Chart.yaml
k8s/helm/yona/values.yaml

* Pass batch service URL everywhere
* Allow app-generated passwords-
* Disable e-mail

YD-474 Enable testing against k8s deployment

---

Jenkinsfile
k8s/02_storage.yaml
k8s/helm/yona/templates/10_deployment_admin.yaml
k8s/helm/yona/values.yaml

* Use yona-default as storage class
* Recycle the storage
* Remove unnecessary volumes from Admin service deployment
* Remove the wipe-database step from the Jenkinsfile as we start with a blank slate every time

YD-475 Small Helm improvements

---

core/src/main/java/nu/yona/server/analysis/entities/Activity.java
core/src/main/java/nu/yona/server/analysis/entities/GoalConflictMessage.java
core/src/main/java/nu/yona/server/messaging/service/MessageDto.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyConnectRequestMessageDto.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyConnectResponseMessageDto.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyDisconnectMessageDto.java
core/src/main/java/nu/yona/server/subscriptions/service/BuddyService.java
core/src/main/java/nu/yona/server/subscriptions/service/UserDto.java
core/src/main/java/nu/yona/server/subscriptions/service/UserPrivateDto.java
core/src/main/java/nu/yona/server/subscriptions/service/UserService.java
core/src/test/java/nu/yona/server/subscriptions/service/UserServiceIntegrationTest.java

Reduced from 84 (1st try)/76 (2nd try) to 31 JDBC statements

YD-470 Reduce queries for GET messages

---

analysisservice/src/main/java/nu/yona/server/analysis/service/AnalysisEngineService.java
analysisservice/src/test/java/nu/yona/server/analysis/service/ActivityServiceTests.java
appservice/src/intTest/groovy/nu/yona/server/ActivityTest.groovy
appservice/src/main/java/nu/yona/server/analysis/rest/UserActivityController.java
appservice/src/main/resources/static/swagger/swagger-spec.yaml
core/src/main/java/nu/yona/server/analysis/entities/DayActivityRepository.java
core/src/main/java/nu/yona/server/analysis/service/ActivityService.java
core/src/main/java/nu/yona/server/subscriptions/service/UserPrivateDto.java
core/src/testUtils/groovy/nu/yona/server/test/Buddy.groovy
core/src/testUtils/groovy/nu/yona/server/test/BudgetGoal.groovy
core/src/testUtils/groovy/nu/yona/server/test/TimeZoneGoal.groovy
core/src/testUtils/groovy/nu/yona/server/test/User.groovy

* Fixed issue in AnalysisEngineService where dayActivity was transient
* Added extra integration test
* Extended the Groovy classes with @ToString

YD-340 Only include own goals when shared with a buddy

---

core/src/test/java/nu/yona/server/analysis/entities/DayActivityTests.java
core/src/test/java/nu/yona/server/analysis/entities/WeekActivityTests.java

YD-477 Refactored spread unit tests, added extra

---

core/src/test/java/nu/yona/server/ThymeleafConfigurationTest.java
core/src/test/java/nu/yona/server/analysis/service/DayActivityDtoTests.java
core/src/test/java/nu/yona/server/analysis/service/WeekActivityDtoTests.java
core/src/test/java/nu/yona/server/goals/service/ActivityCategoryServiceTest.java

Postfixes like "rightResult" removed

YD-477 Renamed tests with less speaking names

---

core/src/main/java/nu/yona/server/subscriptions/service/UserService.java

SonarQube misunderstood the code. Made it more readable, for humans and for SonarQube :)

YD-478 small code tweaks

---

appservice/src/intTest/groovy/nu/yona/server/AbstractAppServiceIntegrationTest.groovy
appservice/src/intTest/groovy/nu/yona/server/ActivityTest.groovy
appservice/src/main/java/nu/yona/server/analysis/rest/ActivityControllerBase.java
appservice/src/main/java/nu/yona/server/analysis/rest/BuddyActivityController.java
appservice/src/main/java/nu/yona/server/analysis/rest/UserActivityController.java
appservice/src/main/resources/static/swagger/swagger-spec.yaml
core/src/main/java/nu/yona/server/analysis/service/ActivityService.java

For:
* User activity overviews (both day and week), with and without buddies
* Buddy activity overviews (both day and week)
Extended the integration tests accordingly

YD-203 Added activity overview self-links

---

analysisservice/src/main/java/nu/yona/server/analysis/service/AnalysisEngineService.java
analysisservice/src/test/java/nu/yona/server/analysis/service/AnalysisEngineServiceTests.java
appservice/src/intTest/groovy/nu/yona/server/ActivityAggregationBatchJobTest.groovy
appservice/src/intTest/groovy/nu/yona/server/AppActivityTest.groovy
core/src/main/java/nu/yona/server/analysis/entities/Activity.java
core/src/main/java/nu/yona/server/analysis/entities/DayActivity.java
core/src/main/java/nu/yona/server/analysis/service/ActivityDto.java
core/src/main/java/nu/yona/server/util/TimeUtil.java
core/src/test/java/nu/yona/server/analysis/entities/ActivityTests.java
core/src/test/java/nu/yona/server/analysis/entities/DayActivityTests.java
core/src/test/java/nu/yona/server/analysis/entities/IntervalActivityTestsBase.java
core/src/test/java/nu/yona/server/analysis/service/ActivityServiceTests.java
core/src/test/java/nu/yona/server/util/TimeUtilTest.java
dbinit/src/main/liquibase/updates/changelog-0005-yd-403.yml
dbinit/src/main/liquibase/updates/updates.yml

Saving app with Activity
Updated algorithm to split up Activity and when to send a new goal conflict message
Fixed a bug that cross-day activity was omitting the last second/minute of the day

YD-403 Record app in activity

---

scripts/smoothwall/9399yona-log-parser
scripts/smoothwall/HandleDansGuardianLog.pl
scripts/smoothwall/yona-log-parser
scripts/yona-logrotate

Init script, boot hook script, and logrotate configuration
to support the Dansguardian category output parser.
See:
http://wiki.yona.nu/display/DEV/Perl+script+to+pass+events+from+SmoothWall+to+the+Yona+server
For details on how to deploy

Init and Logrotate material for handdansguardian parser

---

appservice/src/main/java/nu/yona/server/DOSProtectionService.java

The request on this ticket was to return an 429 upon a DOS attack, but we are currently not rejecting potential DOS requests but delaying them. The delay wasn't logged, but now it is.

YD-200 Log warning on DOS attack

---

core/src/main/java/nu/yona/server/analysis/entities/DayActivityRepository.java
core/src/main/java/nu/yona/server/analysis/entities/WeekActivityRepository.java
core/src/main/java/nu/yona/server/analysis/service/ActivityService.java
core/src/test/java/nu/yona/server/analysis/service/ActivityServiceTest.java

Intervals normally include one end only (so end - start == duration). Updated our code to align with that.

YD-294 Interval end is now exclusive

---

batchservice/src/main/java/nu/yona/server/batch/quartz/jobs/NewDeviceRequestCleanUpQuartzJob.java
batchservice/src/main/java/nu/yona/server/batch/rest/BatchTaskController.java
batchservice/src/main/java/nu/yona/server/batch/service/BatchJobResultDto.java
batchservice/src/main/java/nu/yona/server/batch/service/BatchTaskService.java
core/src/main/java/nu/yona/server/analysis/entities/ActivityCommentMessage.java
core/src/main/java/nu/yona/server/analysis/service/ActivityServiceException.java
core/src/main/java/nu/yona/server/crypto/CryptoException.java
core/src/main/java/nu/yona/server/exceptions/ConfirmationException.java
core/src/main/java/nu/yona/server/exceptions/PinResetRequestConfirmationException.java
core/src/main/java/nu/yona/server/exceptions/SmsException.java
core/src/main/java/nu/yona/server/exceptions/UserOverwriteConfirmationException.java
core/src/main/java/nu/yona/server/exceptions/YonaException.java
core/src/main/java/nu/yona/server/goals/entities/ActivityCategory.java
core/src/main/java/nu/yona/server/goals/entities/GoalChangeMessage.java
core/src/main/java/nu/yona/server/goals/service/ActivityCategoryException.java
core/src/main/java/nu/yona/server/goals/service/GoalServiceException.java
core/src/main/java/nu/yona/server/messaging/service/MessageNotFoundException.java
core/src/main/java/nu/yona/server/properties/SmsProperties.java
core/src/main/java/nu/yona/server/subscriptions/entities/BuddyConnectRequestMessage.java
core/src/main/java/nu/yona/server/subscriptions/entities/BuddyConnectResponseMessage.java
core/src/main/java/nu/yona/server/subscriptions/entities/BuddyDisconnectMessage.java
core/src/main/java/nu/yona/server/subscriptions/entities/ConfirmationCode.java
core/src/main/java/nu/yona/server/subscriptions/entities/NewDeviceRequestRepository.java
core/src/main/java/nu/yona/server/subscriptions/service/DeviceRequestException.java
core/src/main/java/nu/yona/server/subscriptions/service/LDAPUserServiceException.java
core/src/main/java/nu/yona/server/subscriptions/service/NewDeviceRequestService.java
core/src/test/java/nu/yona/server/sms/PlivoSmsServiceTest.java
dbinit/data/QuartzOtherCronTriggers.json
dbinit/data/QuartzOtherJobs.json
dbinit/src/main/docker/update.sh

Along with this, renamed ActivityAggregationBatchJobResultDto into BatchJobResultDto, as the type is generic, fitting any batch job.

YD-100 Remove expired new device requests

---

analysisservice/src/main/java/nu/yona/server/analysis/service/AnalysisEngineService.java
analysisservice/src/test/java/nu/yona/server/analysis/service/AnalysisEngineServiceTest.java
appservice/src/intTest/groovy/nu/yona/server/AppActivityTest.groovy
core/src/main/java/nu/yona/server/analysis/entities/Activity.java
core/src/main/java/nu/yona/server/analysis/entities/ActivityRepository.java
core/src/main/java/nu/yona/server/analysis/entities/DayActivity.java
core/src/main/java/nu/yona/server/properties/AnalysisServiceProperties.java
core/src/main/java/nu/yona/server/util/TimeUtil.java
core/src/test/java/nu/yona/server/analysis/entities/DayActivityTest.java
core/src/testUtils/groovy/nu/yona/server/test/AppService.groovy

* Overlapping activities for the same app are now merged
* Overlapping activities for different apps (or network activity) are now counted once

YD-487 Implemented resilience for duplicate and overlapping activities

---

appservice/src/intTest/groovy/nu/yona/server/ActivityTest.groovy
appservice/src/main/java/nu/yona/server/analysis/rest/UserActivityController.java
appservice/src/main/resources/static/swagger/swagger-spec.yaml
core/src/main/java/nu/yona/server/CoreConfiguration.java
core/src/main/java/nu/yona/server/analysis/service/ActivityDto.java
core/src/main/java/nu/yona/server/analysis/service/ActivityService.java

The path was created for testing purposes, but it's built in a way that it can be used in the app if the need arises, with an integration test and documented in Swagger.

YD-491 Create path to GET raw activities

---

core/src/main/java/nu/yona/server/subscriptions/entities/BuddyAnonymized.java
core/src/main/java/nu/yona/server/subscriptions/service/migration/EncryptBuddyLastStatusChangeTime.java
dbinit/src/main/liquibase/updates/changelog-0006-yd-484.yml
dbinit/src/main/liquibase/updates/updates.yml

* Removed the field from the class
* Removed the logic from EncryptBuddyLastStatusChangeTime
* Added a dropColumn for the column last_status_change_time

YD-484 Remove BuddyAnonymized.lastStatusChangeTime

---

adminservice/src/main/java/nu/yona/server/admin/DashboardController.java
adminservice/src/main/resources/templates/dashboard.html
core/src/main/java/nu/yona/server/subscriptions/entities/UserRepository.java

Added the following structure:
* Users that confirmed their mobile number: 1
* Users that did not confirm their mobile number: 8
** Users invited on buddy request: 6
** Other users: 2

YD-494 Extended the dashboard with user counts

---

core/src/main/resources/application.properties
core/src/main/resources/templates/email/buddy-invitation-body.html
core/src/main/resources/templates/email/messages.properties
core/src/main/resources/templates/email/messages_nl.properties
core/src/test/java/nu/yona/server/ThymeleafConfigurationTest.java

Forgot we have unit tests that verify the template expansion.

YD-502 Corrected the unit tests

---

Jenkinsfile

As discussed (and late) here is the proposed Jenkinsfile changes to add the stages for prompting and deploying to beta.

Add Jenkins pipeline stages for Beta

---

analysisservice/src/main/java/nu/yona/server/analysis/rest/AnalysisEngineController.java

Added a simple request parameter usable with:
```
POST /userAnonymized/{userAnonymizedId}/networkActivity/?preventParallelism=true
```

YD-507 Added request parameter preventParallelism=true for load test purposes

---

adminservice/src/main/java/nu/yona/server/admin/DashboardController.java
adminservice/src/main/resources/templates/dashboard.html

Added the configured maximum number of users and the build number

YD-516 extended dashboard

---

analysisservice/src/main/java/nu/yona/server/analysis/service/AnalysisEngineService.java
appservice/src/main/java/nu/yona/server/analysis/rest/UserActivityController.java
core/src/main/java/nu/yona/server/analysis/entities/Activity.java
core/src/main/java/nu/yona/server/analysis/entities/DayActivity.java
core/src/main/java/nu/yona/server/analysis/service/ActivityDto.java

Made it explicit that activities do not always have an associated device.

YD-525 Fixed NPE during network activity analysis

---

analysisservice/src/main/java/nu/yona/server/analysis/rest/AnalysisEngineController.java
analysisservice/src/main/java/nu/yona/server/analysis/service/ActivityCacheService.java
analysisservice/src/test/java/nu/yona/server/analysis/service/AnalysisEngineServiceTest.java
appservice/src/main/java/nu/yona/server/analysis/rest/ActivityControllerBase.java
appservice/src/main/java/nu/yona/server/device/rest/DeviceController.java
appservice/src/main/java/nu/yona/server/subscriptions/rest/NewDeviceRequestController.java
core/src/main/java/nu/yona/server/analysis/service/AnalysisEngineProxyService.java
core/src/main/java/nu/yona/server/analysis/service/NetworkActivityDto.java
core/src/main/java/nu/yona/server/device/entities/DeviceAnonymized.java
core/src/main/java/nu/yona/server/device/service/DeviceAnonymizedDto.java
core/src/main/java/nu/yona/server/device/service/DeviceServiceException.java
core/src/main/java/nu/yona/server/device/service/UserDeviceDto.java
core/src/main/java/nu/yona/server/rest/Constants.java
core/src/main/java/nu/yona/server/subscriptions/entities/User.java
core/src/main/java/nu/yona/server/subscriptions/entities/UserRepository.java
core/src/main/java/nu/yona/server/subscriptions/service/UserAnonymizedDto.java
core/src/main/java/nu/yona/server/subscriptions/service/UserDto.java
core/src/main/java/nu/yona/server/subscriptions/service/UserService.java
core/src/main/resources/messages/messages.properties
core/src/main/resources/messages/messages_nl.properties
core/src/test/java/nu/yona/server/analysis/entities/ActivityTest.java
core/src/test/java/nu/yona/server/analysis/entities/DayActivityTest.java
core/src/test/java/nu/yona/server/analysis/entities/IntervalActivityTestBase.java
core/src/test/java/nu/yona/server/analysis/service/ActivityServiceTest.java
core/src/test/java/nu/yona/server/device/service/DeviceServiceTest.java
core/src/test/java/nu/yona/server/entities/ActivityRepositoryMock.java
core/src/test/java/nu/yona/server/entities/UserRepositoriesConfiguration.java
core/src/test/java/nu/yona/server/subscriptions/service/BuddyDeviceChangeMessageDtoTest.java
core/src/test/java/nu/yona/server/subscriptions/service/migration/AddFirstDeviceTest.java

* Updated the copyright statements
* The changes of YD-525 caused the build for YD-524 to fail. This is resolved now.

YD-528 Update copyrights and address conflict between change sets

---

Jenkinsfile

Along with this: some small corrections to earlier stages.

YD-531 Added deployment to production

---

appservice/src/intTest/groovy/nu/yona/server/AbstractAppServiceIntegrationTest.groovy
appservice/src/intTest/groovy/nu/yona/server/ActivityTest.groovy
appservice/src/intTest/groovy/nu/yona/server/AddDeviceTest.groovy
appservice/src/intTest/groovy/nu/yona/server/CreateUserOnBuddyRequestTest.groovy
appservice/src/intTest/groovy/nu/yona/server/DeviceTest.groovy
appservice/src/intTest/groovy/nu/yona/server/UserTest.groovy
appservice/src/main/java/nu/yona/server/device/rest/DeviceController.java
appservice/src/main/java/nu/yona/server/subscriptions/rest/UserController.java
appservice/src/main/resources/static/swagger/swagger-spec.yaml
core/build.gradle
core/src/main/java/nu/yona/server/device/service/DeviceService.java
core/src/main/java/nu/yona/server/device/service/DeviceServiceException.java
core/src/main/java/nu/yona/server/device/service/UserDeviceDto.java
core/src/main/java/nu/yona/server/subscriptions/service/UserService.java
core/src/main/resources/messages/messages.properties
core/src/main/resources/messages/messages_nl.properties
core/src/test/java/nu/yona/server/device/service/DeviceServiceTest.java
core/src/test/java/nu/yona/server/subscriptions/service/UserServiceTest.java
core/src/test/java/nu/yona/server/subscriptions/service/migration/AddFirstDeviceTest.java
core/src/testUtils/groovy/nu/yona/server/test/AppService.groovy
core/src/testUtils/groovy/nu/yona/server/test/CommonAssertions.groovy
core/src/testUtils/groovy/nu/yona/server/test/Device.groovy
core/src/testUtils/groovy/nu/yona/server/test/User.groovy

* Moved the path for the app last opened event from the UserController to the DeviceController
* Moved the implementation from the UserService to the DeviceService
* Extended the unit test
* Created an integration test
* Added extra assertions to the integration tests
* Corrected the assertEquals method for a string and a LocalDate in CommonAssertions

YD-526 Register app last opened date on device

---

core/build.gradle

To get the latest phone number metadata

YD-548 Upgrade libphonenumber to 8.9.1

---

k8s/helm/yona/templates/03_job-liquibase.yaml
k8s/helm/yona/templates/10_deployment_admin.yaml
k8s/helm/yona/templates/10_deployment_analysis.yaml
k8s/helm/yona/templates/10_deployment_app.yaml
k8s/helm/yona/templates/10_deployment_batch.yaml
k8s/helm/yona/values.yaml
scripts/wait-for-services.sh

The health check needs to fixed to support the recent revert that went too far, but for good design.

Helm immutable

---

appservice/src/main/java/nu/yona/server/AppServiceApplication.java
core/src/main/java/nu/yona/server/CoreConfiguration.java

It was in AppServiceApplication, but the Batch service needs it too, so moved it to Core.

YD-559 Moved user synchronizer to CoreConfiguration

---

k8s/helm/yona/templates/01_configmap_properties.yaml
k8s/helm/yona/values.yaml

Changing server config helm chart to include changing logging pattern
Set logging pattern to add yona.correlation.id

Changing error settings to include correlation.id

---

scripts/smoothwall/HandleDansGuardianLog.pl

* Uses File::Tail and `cpan File::Tail` on Smoothwall works
Do not know how long it will persist though (through updates).
http://search.cpan.org/~mgrabnar/File-Tail-1.3/Tail.pm
This seems fairly robust instead of trying to develop our own logic
* Since stdin and file tail have different enough setup, split
the core into separate function that the file and stdin will call
* Mode set to 755 because that's where it was during the commit

Update Smoothwall log parser to tail without fifo

---

k8s/helm/yona/templates/02-service_admin.yaml
k8s/helm/yona/templates/02-service_admin_actuator.yaml
k8s/helm/yona/templates/02-service_analysis.yaml
k8s/helm/yona/templates/02-service_analysis_actuator.yaml
k8s/helm/yona/templates/02-service_app.yaml
k8s/helm/yona/templates/02-service_app_actuator.yaml
k8s/helm/yona/templates/02-service_batch.yaml
k8s/helm/yona/templates/02-service_batch_actuator.yaml

To make multiple installs on the same cluster possible

Templating nodeport

---

appservice/src/intTest/groovy/nu/yona/server/UserTest.groovy
appservice/src/main/java/nu/yona/server/subscriptions/rest/UserController.java
core/src/testUtils/groovy/nu/yona/server/test/User.groovy

If the device name is given, all other data must be provided too. If the device name is not provided, the other information cannot be provided either.

YD-595 Assert device info included POST of user

---

dbinit/src/main/docker/update.sh
k8s/helm/yona/templates/03_job-liquibase.yaml

Add environment variable to script, is populated by helm, fixes the activity category updating issues load test was having

dbinit container update

---

appservice/src/intTest/groovy/nu/yona/server/AbstractAppServiceIntegrationTest.groovy
appservice/src/main/java/nu/yona/server/analysis/rest/ActivityControllerBase.java
appservice/src/main/java/nu/yona/server/analysis/rest/BuddyActivityController.java
appservice/src/main/java/nu/yona/server/analysis/rest/UserActivityController.java
appservice/src/main/resources/static/swagger/swagger-spec.yaml

Both for day and week activity details

YD-598 Add buddy link for buddy activity details

---

core/src/main/java/nu/yona/server/CacheConfiguration.java
core/src/main/java/nu/yona/server/CoreConfiguration.java
core/src/main/java/nu/yona/server/goals/service/ActivityCategoryService.java
core/src/main/java/nu/yona/server/subscriptions/service/UserAnonymizedService.java
core/src/test/java/nu/yona/server/goals/service/ActivityCategoryServiceTest.java

The Hazelcast caches don't update metrics unless explicitly registered.

YD-590 Register caches explicitly

---

adminservice/src/intTest/groovy/nu/yona/server/ActivityCategoriesTest.groovy
appservice/src/main/java/nu/yona/server/goals/rest/ActivityCategoryController.java
core/src/main/java/nu/yona/server/goals/service/ActivityCategoryService.java
core/src/testUtils/groovy/nu/yona/server/test/AppService.groovy

Added some code to analyse the problem

YD-607 Add extra logging

---

core/src/main/java/nu/yona/server/messaging/service/MessageService.java
core/src/main/java/nu/yona/server/sms/SmsTemplate.java
core/src/main/resources/templates/sms/direct-message-notification.txt
core/src/main/resources/templates/sms/messages.properties
core/src/main/resources/templates/sms/messages_nl.properties
core/src/test/java/nu/yona/server/messaging/service/MessageServiceTest.java

Sending an SMS with direct messages unless the user was created on buddy request.

YD-605 Send SMS with direct message

---

adminservice/src/main/java/nu/yona/server/admin/DashboardController.java
adminservice/src/main/resources/templates/dashboard.html

- Ensure the percentage is at least 1 with low numbers of users
- Add sums for 30 days

YD-608 Dashboard improvements

---

dbinit/data/productionActivityCategories.json

In all of its video variations

YD-611 Add YouTube

---

build.gradle
core/build.gradle

To see whether spring-projects/spring-hateoas#753 is fixed for us

YD-261 Testing Spring HATEOAS 0.25.1.BUILD-SNAPSHOT

---

adminservice/src/intTest/groovy/nu/yona/server/ActivityCategoriesTest.groovy

- Use interval of 20 seconds because [Hazelcast batch invalidation frequency is by default 10 seconds](https://docs.hazelcast.org/docs/latest/manual/html-single/index.html#near-cache-invalidation)
- Ensure a proper baseline because the number from app service cannot be trusted (unless we add a `waitForCachePropagation` in the `given` part too)

YD-607 Use longer interval and ensure proper baseline

---

k8s/helm/yona/requirements.yaml
k8s/helm/yona/values.yaml

Should be pulled in from the default values.yaml for everything

Make new variable for deploying hazelcast

---

core/build.gradle
core/src/main/java/nu/yona/server/SecurityConfiguration.java
core/src/main/java/nu/yona/server/subscriptions/service/UserAssertionService.java

* Upgraded to Spring Security 5.1.5
* Added security configuration that sets it wide open (as it used to be)

YD-629 Enable HSTS

---

adminservice/src/main/java/nu/yona/server/admin/DashboardController.java
adminservice/src/main/resources/templates/dashboard.html
core/src/main/java/nu/yona/server/subscriptions/entities/UserRepository.java
core/src/test/java/nu/yona/server/entities/UserRepositoryMock.java

Add days opened after app installation to dashboard.

YD-631 Add days opened after app installation to dashboard

---

appservice/src/intTest/groovy/nu/yona/server/DeviceManagementTest.groovy
appservice/src/main/java/nu/yona/server/device/rest/DeviceController.java
core/src/main/java/nu/yona/server/device/service/DeviceRegistrationRequestDto.java
core/src/main/java/nu/yona/server/device/service/DeviceUpdateRequestDto.java

Assert the presence of all mandatory properties of a device registration or update request.

YD-633 Assert presence device request properties

---

core/src/main/java/nu/yona/server/messaging/service/FirebaseService.java
core/src/main/resources/application.properties
k8s/helm/yona/templates/01_configmap_properties.yaml
k8s/helm/yona/templates/01_firebase_secret.yaml
k8s/helm/yona/templates/10_deployment_admin.yaml
k8s/helm/yona/templates/10_deployment_analysis.yaml
k8s/helm/yona/templates/10_deployment_app.yaml
k8s/helm/yona/templates/10_deployment_batch.yaml
k8s/helm/yona/values.yaml

Added the necessary settings and a secret for the service account.

YD-638 Make Firebase Helm-configurable

---

core/src/main/java/nu/yona/server/crypto/CryptoUtil.java
core/src/test/java/nu/yona/server/crypto/CryptoUtilTest.java

YD-650 Temp passwords are now URL-safe

---

analysisservice/src/main/java/nu/yona/server/analysis/service/ActivityUpdateService.java
analysisservice/src/main/java/nu/yona/server/analysis/service/AnalysisEngineService.java
appservice/src/intTest/groovy/nu/yona/server/ActivityTest.groovy
appservice/src/intTest/groovy/nu/yona/server/AnalysisEngineHibernateStatsTest.groovy
appservice/src/intTest/groovy/nu/yona/server/BasicBuddyTest.groovy
appservice/src/main/resources/static/swagger/swagger-spec.yaml
core/src/main/java/nu/yona/server/device/service/DeviceService.java
core/src/main/java/nu/yona/server/device/service/UserDeviceDto.java
core/src/testUtils/groovy/nu/yona/server/test/Device.groovy
core/src/testUtils/groovy/nu/yona/server/test/User.groovy

The property is now set and the integration tests cover it

YD-644 set lastMonitoredActivityDate on device

---

appservice/src/main/java/nu/yona/server/device/rest/DeviceController.java
core/src/main/java/nu/yona/server/properties/AnalysisServiceProperties.java
core/src/main/resources/application.properties

Along with this, removed the warning log about "many messages", as that had no practical value (and > 10 actually isn't many).

YD-651 Increased max app activity count to 200

---

core/src/main/java/nu/yona/server/device/service/DeviceService.java

after updating one of the anonymized devices

YD-682 Save the user anonymized

---

k8s/helm/yona/templates/03_job-liquibase.yaml

Also using this to test helm 2 -> helm 3 in the pipeline

Add helm revision to Job name, so helm upgrades will always trigger it

---

appservice/src/main/java/nu/yona/server/admin/rest/AdminController.java
core/src/main/java/nu/yona/server/subscriptions/entities/User.java
core/src/main/java/nu/yona/server/subscriptions/service/UserAddService.java
core/src/main/java/nu/yona/server/subscriptions/service/UserUpdateService.java

Temporarily, will be removed when implementing the fix

YD-695 Debug logging added

---

core/src/main/java/nu/yona/server/rest/GlobalExceptionMapping.java

Treat RequestRejectedException as invalid request

YD-706 Fix 500-error on unsafe request

---

adminservice/src/main/docker/Dockerfile
analysisservice/src/main/docker/Dockerfile
appservice/src/intTest/groovy/nu/yona/server/ActivityCommentTest.groovy
appservice/src/intTest/groovy/nu/yona/server/ActivityTest.groovy
appservice/src/intTest/groovy/nu/yona/server/DeviceManagementTest.groovy
appservice/src/intTest/groovy/nu/yona/server/DeviceTest.groovy
appservice/src/intTest/groovy/nu/yona/server/OverwriteUserTest.groovy
appservice/src/intTest/groovy/nu/yona/server/RemoveUserTest.groovy
appservice/src/intTest/groovy/nu/yona/server/VpnConnectionStatusEventTest.groovy
appservice/src/main/docker/Dockerfile
batchservice/src/main/docker/Dockerfile
build.gradle
core/src/testUtils/groovy/nu/yona/server/test/CommonAssertions.groovy
gradle/wrapper/gradle-wrapper.properties

To enable that, correct .size into .size() in several Groovy files.

Upgrade to Java 17

---

.github/workflows/build-check-publish.yml
.github/workflows/build-deploy.yml
.github/workflows/pr-build.yml

* Use standard dependency submission action
* Review new dependencies for security issues

Improve dependency management

---

.github/workflows/build-check-publish.yml

Minikube from 1.25.2 to 1.33.1
Kubernetes from 1.24.0 to 1.30.2

Upgrade minikube and k8s
